[tool.poetry]
name = "arcane-facebook"
version = "0.1.0"
description = "Helpers to request facebook API"
readme = "README.md"
authors = ["Arcane <product@arcane.run>"]
packages = [
    { include = "arcane" }
]

[tool.poetry.dependencies]
python = "^3.6"
# arcane-core = "1.0.0" (optional)

facebook_business = "5.0.3"
[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
