[tool.poetry]
name = "sms_bomb"
version = "1.0.1"
description = "Простая библиотека для создания ваших смс-бомберов."
readme = "README.md"
homepage = "https://github.com/zalsy/sms-bomb/"
authors = ["zelsy"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]


[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
