
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-23T16:35:55-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "73883627fed1821e8c86fa8f4e4de51742bf91de",
 "version": "2020.9.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
