[tool.poetry]
name = "jp_aesthetic_terminal"
version = "0.1.0"
authors = ["Anthony Khoudary <ankhoudary12@gmail.com>"]
description = "Program for displaying Random Japanese Text in the terminal"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/ankhoudary12/jp-aesthetic-terminal"
repository = "https://github.com/ankhoudary12/jp-aesthetic-terminal"
keywords = ["japenese","aesthetic"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.2"
requests = "^2.24.0"
desert = "^2020.1.6"
marshmallow = "^3.8.0"


[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
flake8-annotations = "^2.4.0"
flake8-black = "^0.2.1"
flake8-bandit = "^2.1.2"
flake8-import-order = "^0.18.1"
flake8-bugbear = "^20.1.4"
black = { version = "*", allow-prereleases = true }
pytest = "^6.0.1"
coverage = {extras = ["toml"], version = "^5.2.1"}
pytest-cov = "^2.10.1"
pytest-mock = "^3.3.1"
mypy = "^0.782"
typeguard = "^2.9.1"
flake8-docstrings = "^1.5.0"
darglint = "^1.5.4"
sphinx = "^3.2.1"
sphinx-autodoc-typehints = "^1.11.0"

[tool.poetry.scripts]
jp-aesthetic-terminal = "jp_aesthetic_terminal.console:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["jp_aesthetic_terminal"]

[tool.coverage.report]
show_missing = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
