sensor:
  - platform: darksky
    api_key: use_ais_dom_api_key
    forecast: 0
    language: pl
    units: si
    monitored_conditions:
      # A human-readable text summary for the next two days.
      - hourly_summary
      # A human-readable text summary for the next week.
      - daily_summary
      - temperature
      # feels like
      - apparent_temperature
      - wind_speed
      - cloud_cover
      - humidity
      - pressure
      - visibility
    scan_interval:
      hours: 2

