#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['checkrs']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

install_requires = \
['matplotlib',
 'numpy',
 'pandas',
 'past',
 'pkg_resources',
 'scipy',
 'seaborn',
 'sklearn',
 'statsmodels',
 'tqdm']

setup(name='checkrs',
      version='0.1.1',
      description='Tools for simulation-based model checking and diagnostics.',
      author='Timothy Brathwaite',
      author_email='timothyb0912@gmail.com',
      url='https://github.com/timothyb0912/checkrs',
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      install_requires=install_requires,
      python_requires='>=3.3',
     )
