[tool.poetry]
name = "delphai-utils"
version = "0.1.4"
description = "delphai backend utilities"
authors = ["Barath Kumar <barath@delphai.com>"]
homepage = "https://github.com/delphai/backend-utils"

[tool.poetry.dependencies]
python = "^3.8"
omegaconf = "^2.0.2"
memoization = "^0.3.1"
python-dotenv = "^0.14.0"
kubernetes = "^11.0.0"
coloredlogs = "^14.0"
deepmerge = "^0.1.0"
pytest-watch = "^4.2.0"
grpcio = "^1.32.0"
starlette = "^0.13.8"
hypercorn = "^0.10.2"
grpc_requests = "^0.0.5"
validate_email = "^1.3"
ipaddress = "^1.0.23"
jinja2 = "^2.11.2"
markupsafe = "^1.1.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
yapf = "^0.30.0"
poethepoet = "^0.8.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poe.tasks]
test = "ptw -- --verbose"
publish-test = "poetry publish -r testpypi"
publish = [
  {cmd = "poetry version patch"},
  {cmd = "poetry build"},
  {cmd = "poetry publish"},
  {cmd = "poetry publish -r testpypi"}
]