[tool.poetry]
name = "confdsl"
version = "0.1.0"
description = "wrapper to make reading config from various DSLs easy"
authors = ["Ayush <ayushshanker@outlook.in>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
pyhcl = "^0.4.4"

[tool.poetry.dev-dependencies]
black = "^20.8b1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
