[tool.poetry]
name = "social-auth-backend-epita"
version = "1.0.1"
description = "EPITA backend for python-social-auth"
license = "AGPL-3.0"
authors = ["Marin Hannache <mareo@cri.epita.fr>"]
repository="https://gitlab.cri.epita.fr/cri/packages/social-auth-backend-epita"
readme = "README.md"
classifiers=[
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.8"
social-auth-core = {extras = ["openidconnect"], version = "^3.3.3"}

[tool.poetry.dev-dependencies]
pre-commit = "^2.6.0"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
