[tool.poetry]
name = "naviance"
version = "0.1.0"
description = ""
authors = ["Charlie Bini <cbini87@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
selenium = "^3.141.0"
beautifulsoup4 = "^4.9.2"
python-dateutil = "^2.8.1"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
