# Generated by Django 3.0.6 on 2020-09-20 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('genviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericGlobalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ED', 'Modification'), ('DE', 'Suppression'), ('NE', 'Création')], default='ED', max_length=2)),
                ('history_object_id', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('changeReason', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('history_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
