# Generated by Django 3.0.6 on 2020-09-21 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genviews', '0003_auto_20200920_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericuser',
            name='style',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='genviews.Style', verbose_name='Style'),
            preserve_default=False,
        ),
    ]
