# Generated by Django 3.1.1 on 2020-09-27 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genviews', '0004_auto_20200921_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='genericuser',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='genviews.style', verbose_name='Style'),
        ),
    ]
