name: Test Python Package

on:
  push:
    branches:
      - '*'
  repository_dispatch:
    types: manual-trigger

jobs:
  build:
    if: contains(toJson(github.event.commits), '[skip ci]') == false && contains(toJson(github.event.commits), '[skip github]') == false

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]
        exclude:
          - os: macos-latest
            python-version: 3.6
          - os: macos-latest
            python-version: 3.7
          - os: ubuntu-latest
            python-version: 3.7
          - os: windows-latest
            python-version: 3.6
          - os: windows-latest
            python-version: 3.7

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        echo "::set-env name=OS_PY_VERS::${{ matrix.os }}_${{ matrix.python-version }}"
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r dev-requirements.txt
        
    - name: Lint with flake8 (only Ubuntu/Python 3.8)
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.8'
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-line-length=127 --statistics

    - name: Test with tox (except Ubuntu/Python 3.7)
      if: ${{ env.OS_PY_VERS }} != 'ubuntu-latest_3.7'
      run: |
        tox -e py-cov
