[tool.poetry]
name = "aminoraid"
version = "1.1.2"
description = ""
authors = ["Some Community <olegskvorcovn1@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
"Amino.py" = "1.1.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
