[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "apiera"
author = "Jérôme Krell"
author-email = "jerome.krell@bluewin.ch"
home-page = "https://github.com/JeromeK13/hapi"
classifiers = ["License :: OSI Approved :: MIT License"]
description-file = "README.md"
requires = [
    "click==7.1.2",
    "Cython==0.29.21",
    "h11==0.9.0",
    "starlette==0.13.8",
    "uvicorn==0.11.8",
    "websockets==8.1"
]
