[tool.poetry]
name = "time-int"
version = "0.0.9"
description = "Subclass of integer representing seconds since UNIX epoch"
authors = ["Andrew Allaire <andrew.allaire@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/aallaire/time-int"
repository = "https://github.com/aallaire/time-int"


[tool.poetry.dependencies]
python = "^3.5"
pytest = "^5.4.2"
magic-kind = "^0.2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
