[tool.poetry]
name = "Redditsfinder"
version = "0.1.1"
description = "Lints Python code blocks in Markdown files using flake8"
authors = ["fitzy1293 <berkshiremind@gmail.com>"]
# New attributes
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Fitzy1293/redditsfinder"
repository = "https://github.com/Fitzy1293/redditsfinder"
keywords = ["reddit", "webscraping", "reddit-crawler", "pushshift"]
classifiers = [
    "Environment :: Console",
    "Framework :: Flake8",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Documentation",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Quality Assurance",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
# Updated Python version
python = "^3.6"
rich = "^7.0.0"
redditcleaner = "^1.1.2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
redditsfinder = 'redditsfinder:main'


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
