[build-system]
requires = [
    "robotpy-build>=2020.2.0,<2021.0.0",
    "robotpy-wpiutil>=2020.2.2.0,<2021.0.0",
    "wpilib>=2020.2.2.0"
]

[tool.robotpy-build]
base_package = "rev"

[tool.robotpy-build.wrappers."rev._sparkmaxdriver".maven_lib_download]
artifact_id = "SparkMax-driver"
group_id = "com.revrobotics.frc"
repo_url = "http://www.revrobotics.com/content/sw/max/sdk/maven"
version = "1.5.2"

libs = ["SparkMaxDriver"]

[tool.robotpy-build.wrappers."rev._sparkmaxdriver"]
name = "rev_spark_driver"
depends = ["wpilib_core", "wpiutil"]

sources = [
    "rev/_sparkmaxdriver/sparkmaxdriver.cpp"
]

generate = [
    { CANSparkMaxFrames = "rev/CANSparkMaxFrames.h" },
]
generation_data = "gen/driver"

[tool.robotpy-build.wrappers."rev".maven_lib_download]
artifact_id = "SparkMax-cpp"
group_id = "com.revrobotics.frc"
repo_url = "http://www.revrobotics.com/content/sw/max/sdk/maven"
version = "1.5.2"

libs = ["SparkMax"]

[tool.robotpy-build.wrappers."rev"]
name = "rev"
sources = [
    "rev/rev.cpp"
]

depends = ["wpilibc", "wpilib_core", "wpiutil", "rev_spark_driver"]

generate = [
    { CANSparkMaxLowLevel = "rev/CANSparkMaxLowLevel.h" },
    { CANSparkMax = "rev/CANSparkMax.h" },

    { CANAnalog = "rev/CANAnalog.h" },
    # { CANDeviceScanner = "rev/CANDeviceScanner.h" },
    { CANDigitalInput = "rev/CANDigitalInput.h" },
    { CANEncoder = "rev/CANEncoder.h" },
    { CANError = "rev/CANError.h" },
    { CANPIDController = "rev/CANPIDController.h" },
    { CANSensor = "rev/CANSensor.h" },
    { ControlType = "rev/ControlType.h" },
    { SparkMax = "rev/SparkMax.h" },
]

generation_data = "gen"

[tool.robotpy-build.metadata]
name = "robotpy-rev"
description = "Rev Robotics Spark Max SDK for RobotPy"
author = "RobotPy Development Team"
author_email = "robotpy@googlegroups.com"
url = "https://github.com/robotpy/robotpy-rev"
license = "BSD-3-Clause"
install_requires = [
    "robotpy-wpiutil>=2020.2.2.0,<2021.0.0",
    "wpilib>=2020.2.2.0"
]
