stages:
  - test
  - package
  - deploy


.test_template: &test_definition
  script:
    - .ci/run_tests.sh
  artifacts:
    paths:
      - python/cover
      - public
    when: always
    expire_in: 1 week

slc6:
  <<: *test_definition
  image: gitlab-registry.cern.ch/lhcb-docker/python-deployment:slc6

centos7:
  <<: *test_definition
  image: gitlab-registry.cern.ch/lhcb-docker/python-deployment:centos7

centos8:
  <<: *test_definition
  image: gitlab-registry.cern.ch/lhcb-docker/os-base/centos8-base:latest


python2.7:
  <<: *test_definition
  image: gitlab-registry.cern.ch/lhcb-docker/python-deployment:python-2.7

python3.5:
  <<: *test_definition
  image: gitlab-registry.cern.ch/lhcb-docker/python-deployment:python-3.5

python3.6:
  <<: *test_definition
  image: gitlab-registry.cern.ch/lhcb-docker/python-deployment:python-3.6

python3.7:
  <<: *test_definition
  image: gitlab-registry.cern.ch/lhcb-docker/python-deployment:python-3.7

formatting:
  image: gitlab-registry.cern.ch/lhcb-docker/python-deployment:python-3.7
  script:
    - pip install black
    - black --check .

# Singularity
.singularity_template: &singularity_definition
  <<: *test_definition
  # Use specific version of the official docker client image (as well as the docker-in-docker image) as recommended by
  # https://about.gitlab.com/2019/07/31/docker-in-docker-with-docker-19-dot-03/
  # https://gitlab.cern.ch/gitlabci-examples/demo-privileged-runners/blob/master/.gitlab-ci.yml
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  tags:
    # "docker run --privileged" is required to use singularity
    - docker-privileged
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    # Mount CVMFS on the host
    # See: https://cern.service-now.com/service-portal/article.do?n=KB0005851
    - docker run -d --name cvmfs --pid=host --user 0 --privileged --restart always -v /shared-mounts:/cvmfsmounts:rshared gitlab-registry.cern.ch/vcs/cvmfs-automounter:master
  script:
    # Run the tests
    - docker run --rm --privileged -v /shared-mounts/cvmfs:/cvmfs:rslave -v $CI_PROJECT_DIR:$CI_PROJECT_DIR -w $CI_PROJECT_DIR $IMAGE_FOR_TESTING .ci/run_tests.sh PATCH_COVERAGE

slc6-singularity:
  <<: *singularity_definition
  variables:
    IMAGE_FOR_TESTING: gitlab-registry.cern.ch/lhcb-docker/python-singularity:slc6-singularity

centos7-singularity:
  <<: *singularity_definition
  variables:
    IMAGE_FOR_TESTING: gitlab-registry.cern.ch/lhcb-docker/python-singularity:centos7-singularity

slc6-singularity-latest:
  <<: *singularity_definition
  variables:
    IMAGE_FOR_TESTING: gitlab-registry.cern.ch/lhcb-docker/python-singularity:slc6-singularity-latest

centos7-singularity-latest:
  <<: *singularity_definition
  variables:
    IMAGE_FOR_TESTING: gitlab-registry.cern.ch/lhcb-docker/python-singularity:centos7-singularity-latest

centos8-singularity:
  <<: *singularity_definition
  variables:
    IMAGE_FOR_TESTING: gitlab-registry.cern.ch/lhcb-docker/python-singularity:centos8-singularity-latest

python-2.7-singularity:
  <<: *singularity_definition
  variables:
    IMAGE_FOR_TESTING: gitlab-registry.cern.ch/lhcb-docker/python-singularity:python-2.7-singularity

python-3.5-singularity:
  <<: *singularity_definition
  variables:
    IMAGE_FOR_TESTING: gitlab-registry.cern.ch/lhcb-docker/python-singularity:python-3.5-singularity

python-3.6-singularity:
  <<: *singularity_definition
  variables:
    IMAGE_FOR_TESTING: gitlab-registry.cern.ch/lhcb-docker/python-singularity:python-3.6-singularity

python-3.7-singularity:
  <<: *singularity_definition
  variables:
    IMAGE_FOR_TESTING: gitlab-registry.cern.ch/lhcb-docker/python-singularity:python-3.7-singularity

# Packaging step
deploy-packages:
  stage: deploy
  only:
    - tags
  dependencies: []
  image: gitlab-registry.cern.ch/lhcb-docker/python-deployment:python-3.7
  script:
    - python setup.py sdist --dist-dir public/
    - python setup.py bdist_wheel --dist-dir public/
    - if [ -z "$TWINE_PASSWORD" ] ; then echo "Set TWINE_PASSWORD in CI variables" ; exit 1 ; fi
    - twine upload -u __token__ public/*
  before_script: []
  after_script: []
