[tool.poetry]
name = "smpw"
version = "1.0.5"
description = "modile hack python is windows 10"
authors = ["John Smith <azarovnick@bk.ru>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
