[tool.poetry]
name = "figuresToPhoto"
version = "1.0.1"
description = "figures(\"test.png\").squareToJpg(20,20,100,100,\"black\",\"blackTest\")"
authors = ["RealGames70 <69468716+RealGames70@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
