[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "dlcu"
author = "fcatus"
author-email = "f.catus@pm.me"
home-page = "https://github.com/bchaselab/dlcu"

