[tool.poetry]
name = "pypfb"
version = "0.5.0"
description = "Python SDK for PFB format"
authors = ["CTDS UChicago <cdis@uchicago.edu>"]
license = "Apache-2.0"
packages = [
    { include = "pfb", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.1.2"
fastavro = "^1.0.0"
python-json-logger = "^0.1.11"
PyYAML = "^5.3.1"
importlib_metadata = { version = "^1.3.0", python = "<3.8" }
dictionaryutils = "<=3.0.2"
gdcdictionary = "^1.2.0"

[tool.poetry.dev-dependencies]
codacy-coverage = "*"
pytest = "~=3.2"
pytest-cov = "~=2.5"
truffleHog = "*"
gen3git = "*"

[tool.poetry.scripts]
pfb = 'pfb.cli:main'

[tool.poetry.plugins."pfb.plugins"]
"from_gen3dict" = "pfb.importers.gen3dict"
"from_json" = "pfb.importers.json"
"to_gremlin" = "pfb.exporters.gremlin"
"show" = "pfb.commands.show"
"add" = "pfb.commands.add"
"rename" = "pfb.commands.rename"
"to_tsv" = "pfb.exporters.tsv"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
