from typing import Any

DESCRIPTOR: Any
KeywordInfo: Any
PlacementInfo: Any
MobileAppCategoryInfo: Any
MobileApplicationInfo: Any
LocationInfo: Any
DeviceInfo: Any
PreferredContentInfo: Any
ListingGroupInfo: Any
ListingScopeInfo: Any
ListingDimensionInfo: Any
HotelIdInfo: Any
HotelClassInfo: Any
HotelCountryRegionInfo: Any
HotelStateInfo: Any
HotelCityInfo: Any
ProductBiddingCategoryInfo: Any
ProductBrandInfo: Any
ProductChannelInfo: Any
ProductChannelExclusivityInfo: Any
ProductConditionInfo: Any
ProductCustomAttributeInfo: Any
ProductItemIdInfo: Any
ProductTypeInfo: Any
UnknownListingDimensionInfo: Any
HotelDateSelectionTypeInfo: Any
HotelAdvanceBookingWindowInfo: Any
HotelLengthOfStayInfo: Any
HotelCheckInDayInfo: Any
InteractionTypeInfo: Any
AdScheduleInfo: Any
AgeRangeInfo: Any
GenderInfo: Any
IncomeRangeInfo: Any
ParentalStatusInfo: Any
YouTubeVideoInfo: Any
YouTubeChannelInfo: Any
UserListInfo: Any
ProximityInfo: Any
GeoPointInfo: Any
AddressInfo: Any
TopicInfo: Any
LanguageInfo: Any
IpBlockInfo: Any
ContentLabelInfo: Any
CarrierInfo: Any
UserInterestInfo: Any
WebpageInfo: Any
WebpageConditionInfo: Any
OperatingSystemVersionInfo: Any
AppPaymentModelInfo: Any
MobileDeviceInfo: Any
CustomAffinityInfo: Any
CustomIntentInfo: Any
LocationGroupInfo: Any
