
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-23T13:33:27+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "a841bd48d51edb906a323f3e3c10eb6fd2e33248",
 "version": "1.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
