
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-20T13:02:56-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9ce1049930dd4c643ad8c5373e92a729e603b25f",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
