
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-20T20:35:41-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "6805865e39809274ab0f6b396629d0f383c805dc",
 "version": "0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
