[tool.poetry]
name = "rich_sparklines"
version = "0.1.1"
description = "Integrate rich and sparklines libraries"
authors = ["Elliana <me@mause.me>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
rich = "^7.1.0"
sparklines = "^0.4.2"

[tool.poetry.dev-dependencies]
pytest = "^6.1.0"
pre-commit = "^2.7.1"
rope = "^0.17.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
