# coding: utf-8

"""
    XENON PMT API

    API for the XENON PMT database  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: joe.mosbacher@gmail.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import xepmts
from xepmts.api.nveto_pmt_api import NvetoPmtApi  # noqa: E501
from xepmts.rest import ApiException


class TestNvetoPmtApi(unittest.TestCase):
    """NvetoPmtApi unit test stubs"""

    def setUp(self):
        self.api = xepmts.api.nveto_pmt_api.NvetoPmtApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_nveto_pmt_item(self):
        """Test case for delete_nveto_pmt_item

        Deletes a NvetoPmt document  # noqa: E501
        """
        pass

    def test_get_nveto_pmt_item(self):
        """Test case for get_nveto_pmt_item

        Retrieves a NvetoPmt document  # noqa: E501
        """
        pass

    def test_get_nveto_pmt_item_by_serial_number(self):
        """Test case for get_nveto_pmt_item_by_serial_number

        Retrieves a NvetoPmt document by serial_number  # noqa: E501
        """
        pass

    def test_get_nveto_pmts(self):
        """Test case for get_nveto_pmts

        Retrieves one or more NvetoPmts  # noqa: E501
        """
        pass

    def test_patch_nveto_pmt_item(self):
        """Test case for patch_nveto_pmt_item

        Updates a NvetoPmt document  # noqa: E501
        """
        pass

    def test_post_nveto_pmts(self):
        """Test case for post_nveto_pmts

        Stores one or more NvetoPmts.  # noqa: E501
        """
        pass

    def test_put_nveto_pmt_item(self):
        """Test case for put_nveto_pmt_item

        Replaces a NvetoPmt document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
