# coding: utf-8

"""
    XENON PMT API

    API for the XENON PMT database  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: joe.mosbacher@gmail.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import xepmts
from xepmts.api.tpc_afterpulse_api import TpcAfterpulseApi  # noqa: E501
from xepmts.rest import ApiException


class TestTpcAfterpulseApi(unittest.TestCase):
    """TpcAfterpulseApi unit test stubs"""

    def setUp(self):
        self.api = xepmts.api.tpc_afterpulse_api.TpcAfterpulseApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_tpc_afterpulse_item(self):
        """Test case for delete_tpc_afterpulse_item

        Deletes a TpcAfterpulse document  # noqa: E501
        """
        pass

    def test_get_tpc_afterpulse_item(self):
        """Test case for get_tpc_afterpulse_item

        Retrieves a TpcAfterpulse document  # noqa: E501
        """
        pass

    def test_get_tpc_afterpulses(self):
        """Test case for get_tpc_afterpulses

        Retrieves one or more TpcAfterpulses  # noqa: E501
        """
        pass

    def test_patch_tpc_afterpulse_item(self):
        """Test case for patch_tpc_afterpulse_item

        Updates a TpcAfterpulse document  # noqa: E501
        """
        pass

    def test_post_tpc_afterpulses(self):
        """Test case for post_tpc_afterpulses

        Stores one or more TpcAfterpulses.  # noqa: E501
        """
        pass

    def test_put_tpc_afterpulse_item(self):
        """Test case for put_tpc_afterpulse_item

        Replaces a TpcAfterpulse document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
