[tool.poetry]
name = "typing_copilot"
version = "0.5.4"
description = "Helper for starting to type-hint large codebases with mypy."
authors = ["Predrag Gruevski <obi1kenobi82@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"


[tool.poetry.dev-dependencies]
jupyterlab = "^2.1.5"
mypy = "^0.782"
black = "==20.8b1"
flake8 = "^3.6.0"
click = "^7.1.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 100
