### XXX DOCS SHOULD INCLUDE LINKCHECK BUT IT'S BUSTED ON CURRENT SPHINX (3.1, 2020-Jun-17):
### https://github.com/sphinx-doc/sphinx/issues/7806

language: c

os:
  - linux
  - osx

sudo: false

# Don't CI branches besides master. PR's still get built -- this just prevents
# PR branches from being built twice in the standard workflow.
branches:
  only:
    - master

notifications:
  email: false

env:
  global:
    - CONDA_CHANNELS="conda-forge"
    - CONDA_DEPENDENCIES="astropy coveralls cython healpy numpydoc openexr-python pillow pytest-cov pyyaml sphinx sphinx-automodapi tqdm"
    - PIP_DEPENDENCIES="astropy-sphinx-theme wwt_data_formats"
  matrix:
    - PYTHON_VERSION=3.7
    - PYTHON_VERSION=3.8

install:
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh

script:
  - python setup.py sdist
  - cd dist && pip install *.tar.gz --verbose && cd ..
  - python setup.py build_ext --inplace
  - py.test --cov toasty toasty
  # Different stdlib organization breaks API doc files on Python 2:
  - if [[ $PYTHON_VERSION == 3.7 ]] ; then make -C docs html ; fi

after_success:
  - coveralls
