
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-28T12:12:45-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "320e726dfffc90451c972939b2edea038083e385",
 "version": "2020.9.28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
