# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from hydro_serving_grpc.gateway import api_pb2 as hydro__serving__grpc_dot_gateway_dot_api__pb2
from hydro_serving_grpc.tf.api import predict_pb2 as hydro__serving__grpc_dot_tf_dot_api_dot_predict__pb2


class GatewayServiceStub(object):
  """Extensions to the PredictionService API for a gateway
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ReplayModel = channel.unary_unary(
        '/hydrosphere.serving.gateway.GatewayService/ReplayModel',
        request_serializer=hydro__serving__grpc_dot_gateway_dot_api__pb2.ReplayRequest.SerializeToString,
        response_deserializer=hydro__serving__grpc_dot_tf_dot_api_dot_predict__pb2.PredictResponse.FromString,
        )
    self.PredictServable = channel.unary_unary(
        '/hydrosphere.serving.gateway.GatewayService/PredictServable',
        request_serializer=hydro__serving__grpc_dot_gateway_dot_api__pb2.ServablePredictRequest.SerializeToString,
        response_deserializer=hydro__serving__grpc_dot_tf_dot_api_dot_predict__pb2.PredictResponse.FromString,
        )
    self.ShadowlessPredictServable = channel.unary_unary(
        '/hydrosphere.serving.gateway.GatewayService/ShadowlessPredictServable',
        request_serializer=hydro__serving__grpc_dot_gateway_dot_api__pb2.ServablePredictRequest.SerializeToString,
        response_deserializer=hydro__serving__grpc_dot_tf_dot_api_dot_predict__pb2.PredictResponse.FromString,
        )


class GatewayServiceServicer(object):
  """Extensions to the PredictionService API for a gateway
  """

  def ReplayModel(self, request, context):
    """Makes prediction with specified date
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PredictServable(self, request, context):
    """Send prediction request to specified servable.Sends data to shadow.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ShadowlessPredictServable(self, request, context):
    """Makes prediction but doesn't send it to shadow
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GatewayServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ReplayModel': grpc.unary_unary_rpc_method_handler(
          servicer.ReplayModel,
          request_deserializer=hydro__serving__grpc_dot_gateway_dot_api__pb2.ReplayRequest.FromString,
          response_serializer=hydro__serving__grpc_dot_tf_dot_api_dot_predict__pb2.PredictResponse.SerializeToString,
      ),
      'PredictServable': grpc.unary_unary_rpc_method_handler(
          servicer.PredictServable,
          request_deserializer=hydro__serving__grpc_dot_gateway_dot_api__pb2.ServablePredictRequest.FromString,
          response_serializer=hydro__serving__grpc_dot_tf_dot_api_dot_predict__pb2.PredictResponse.SerializeToString,
      ),
      'ShadowlessPredictServable': grpc.unary_unary_rpc_method_handler(
          servicer.ShadowlessPredictServable,
          request_deserializer=hydro__serving__grpc_dot_gateway_dot_api__pb2.ServablePredictRequest.FromString,
          response_serializer=hydro__serving__grpc_dot_tf_dot_api_dot_predict__pb2.PredictResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hydrosphere.serving.gateway.GatewayService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
