[tool.poetry]
authors = [
  "Tiago Requeijo <tiago.requeijo.dev@gmail.com>",
]
description = "A library to load configuration parameters from multiple sources and formats"
homepage = "https://github.com/tr11/python-configuration"
include = ["config/py.typed"]
keywords = ['configuration', 'settings', 'json', 'yaml', 'toml', 'ini']
license = "MIT"
name = "python-configuration"
packages = [
  {include = "config"},
]
readme = 'README.md'
repository = "https://github.com/tr11/python-configuration"
version = "0.8.1"

[tool.poetry.dependencies]
azure-identity = {version = "^1.1.0", optional = true}
azure-keyvault = {version = "^4.0.0", optional = true}
boto3 = {version = "^1.10.48", optional = true}
google-cloud-secret-manager = {version = "^1.0.0", optional = true}
python = "^3.6"
pyyaml = {version = "^5.1", optional = true}
toml = {version = "^0.10.0", optional = true}

[tool.poetry.dev-dependencies]
flake8-blind-except = "^0.1.1"
flake8-bugbear = "^19.0"
flake8-builtins = "^1.4"
flake8-comprehensions = "^2.0"
flake8-docstrings = "^1.3"
flake8-import-order = "^0.18.0"
mypy = "^0.730"
pydocstyle = "^4.0"
pytest = "^5.0"
pytest-black = "^0.3.7"
pytest-cov = "^2.6"
pytest-flake8 = "^1.0"
pytest-mock = "^2.0.0"
pytest-mypy = "^0.4.1"
sphinx = "^2.1"
sphinx-autodoc-typehints = "^1.6"
# need to allow pre-releases to address a recent change in pytest-black. See https://github.com/shopkeep/pytest-black/issues/45
black = {version = "*", allow-prereleases = true}

[tool.poetry.extras]
aws = ["boto3"]
azure = ["azure-keyvault", "azure-identity"]
gcp = ["google-cloud-secret-manager"]
toml = ["toml"]
yaml = ["pyyaml"]

[tool.black]
line-length = 88

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = true
envlist = py36, py37, py38

[testenv]
whitelist_externals = poetry
commands =
    poetry install -v -E toml -E yaml -E azure -E aws
    poetry run pytest
"""

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=1.0.0"]
