# coding: utf-8

# flake8: noqa

"""
    Nomad CBEC

    This is the API descriptor for the Nomad CBEC, responsible for CBEC customer ID check. Developed by `Samarkand Global <https://samarkand.global>`_ Check out the detailed `changelog <https://gitlab.com/samarkand-nomad/nomad_readme/-/raw/master/history/nomad_pilot.md>`_. - Install for node with ``npm install nomad_pilot_cli`` - Install for python with ``pip install nomad-pilot-cli``  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: paul@samarkand.global
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.2.0"

# import apis into sdk package
from nomad_cbec_id_cli.api.health_api import HealthApi
from nomad_cbec_id_cli.api.user_api import UserApi

# import ApiClient
from nomad_cbec_id_cli.api_client import ApiClient
from nomad_cbec_id_cli.configuration import Configuration
from nomad_cbec_id_cli.exceptions import OpenApiException
from nomad_cbec_id_cli.exceptions import ApiTypeError
from nomad_cbec_id_cli.exceptions import ApiValueError
from nomad_cbec_id_cli.exceptions import ApiKeyError
from nomad_cbec_id_cli.exceptions import ApiException
# import models into sdk package
from nomad_cbec_id_cli.models.api_response import ApiResponse
from nomad_cbec_id_cli.models.api_response_data import ApiResponseData

