# Version file autogenerated by the build process
version = '0.7.9rc1'
build = '553'
vcs_info = 'Git SHA1 65137355 committed on 2020-09-22'

if __name__ == '__main__':
    print('KSCONF_VERSION="0.7.9rc1"\nKSCONF_BUILD="553"\nKSCONF_VCS_INFO="Git SHA1 65137355 committed on 2020-09-22"')
