[tool.poetry]
name = "pytsmod"
version = "0.1.0"
description = ""
authors = ["Sangeon Yong <koragon2@kaist.ac.kr>"]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.19.2"
nptyping = "^1.3.0"
data-science-types = "^0.2.17"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8.3"

# [tool.poetry.scripts]
# tsmod = 'pytsmod.console:run'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
