# coding: utf-8

"""
    XENON PMT API

    API for the XENON PMT database  # noqa: E501

    The version of the OpenAPI document: 0.2
    Contact: joe.mosbacher@gmail.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import xepmts
from xepmts.api.muveto_pmt1_t_api import MuvetoPmt1TApi  # noqa: E501
from xepmts.rest import ApiException


class TestMuvetoPmt1TApi(unittest.TestCase):
    """MuvetoPmt1TApi unit test stubs"""

    def setUp(self):
        self.api = xepmts.api.muveto_pmt1_t_api.MuvetoPmt1TApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_muveto_pmt1_t_item(self):
        """Test case for delete_muveto_pmt1_t_item

        Deletes a MuvetoPmt1T document  # noqa: E501
        """
        pass

    def test_get_muveto_pmt1_t_item(self):
        """Test case for get_muveto_pmt1_t_item

        Retrieves a MuvetoPmt1T document  # noqa: E501
        """
        pass

    def test_get_muveto_pmt1_t_item_by_serial_number(self):
        """Test case for get_muveto_pmt1_t_item_by_serial_number

        Retrieves a MuvetoPmt1T document by serial_number  # noqa: E501
        """
        pass

    def test_get_muveto_pmts1_t(self):
        """Test case for get_muveto_pmts1_t

        Retrieves one or more MuvetoPmts1T  # noqa: E501
        """
        pass

    def test_post_muveto_pmts1_t(self):
        """Test case for post_muveto_pmts1_t

        Stores one or more MuvetoPmts1T.  # noqa: E501
        """
        pass

    def test_put_muveto_pmt1_t_item(self):
        """Test case for put_muveto_pmt1_t_item

        Replaces a MuvetoPmt1T document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
