# coding: utf-8

"""
    XENON PMT API

    API for the XENON PMT database  # noqa: E501

    The version of the OpenAPI document: 0.2
    Contact: joe.mosbacher@gmail.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import xepmts
from xepmts.api.muveto_dark_count_rate1_t_api import MuvetoDarkCountRate1TApi  # noqa: E501
from xepmts.rest import ApiException


class TestMuvetoDarkCountRate1TApi(unittest.TestCase):
    """MuvetoDarkCountRate1TApi unit test stubs"""

    def setUp(self):
        self.api = xepmts.api.muveto_dark_count_rate1_t_api.MuvetoDarkCountRate1TApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_muveto_dark_count_rate1_t_item(self):
        """Test case for delete_muveto_dark_count_rate1_t_item

        Deletes a MuvetoDarkCountRate1T document  # noqa: E501
        """
        pass

    def test_get_muveto_dark_count_rate1_t_item(self):
        """Test case for get_muveto_dark_count_rate1_t_item

        Retrieves a MuvetoDarkCountRate1T document  # noqa: E501
        """
        pass

    def test_get_muveto_dark_count_rates1_t(self):
        """Test case for get_muveto_dark_count_rates1_t

        Retrieves one or more MuvetoDarkCountRates1T  # noqa: E501
        """
        pass

    def test_post_muveto_dark_count_rates1_t(self):
        """Test case for post_muveto_dark_count_rates1_t

        Stores one or more MuvetoDarkCountRates1T.  # noqa: E501
        """
        pass

    def test_put_muveto_dark_count_rate1_t_item(self):
        """Test case for put_muveto_dark_count_rate1_t_item

        Replaces a MuvetoDarkCountRate1T document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
