# coding: utf-8

"""
    XENON PMT API

    API for the XENON PMT database  # noqa: E501

    The version of the OpenAPI document: 0.2
    Contact: joe.mosbacher@gmail.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import xepmts
from xepmts.models.respone_metadata import ResponeMetadata  # noqa: E501
from xepmts.rest import ApiException

class TestResponeMetadata(unittest.TestCase):
    """ResponeMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ResponeMetadata
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = xepmts.models.respone_metadata.ResponeMetadata()  # noqa: E501
        if include_optional :
            return ResponeMetadata(
                page = '0', 
                total = 56, 
                max_results = 56
            )
        else :
            return ResponeMetadata(
        )

    def testResponeMetadata(self):
        """Test ResponeMetadata"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
