# coding: utf-8

"""
    XENON PMT API

    API for the XENON PMT database  # noqa: E501

    The version of the OpenAPI document: 0.2
    Contact: joe.mosbacher@gmail.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import xepmts
from xepmts.api.muveto_gain_api import MuvetoGainApi  # noqa: E501
from xepmts.rest import ApiException


class TestMuvetoGainApi(unittest.TestCase):
    """MuvetoGainApi unit test stubs"""

    def setUp(self):
        self.api = xepmts.api.muveto_gain_api.MuvetoGainApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_muveto_gain_item(self):
        """Test case for delete_muveto_gain_item

        Deletes a MuvetoGain document  # noqa: E501
        """
        pass

    def test_get_muveto_gain_item(self):
        """Test case for get_muveto_gain_item

        Retrieves a MuvetoGain document  # noqa: E501
        """
        pass

    def test_get_muveto_gains(self):
        """Test case for get_muveto_gains

        Retrieves one or more MuvetoGains  # noqa: E501
        """
        pass

    def test_post_muveto_gains(self):
        """Test case for post_muveto_gains

        Stores one or more MuvetoGains.  # noqa: E501
        """
        pass

    def test_put_muveto_gain_item(self):
        """Test case for put_muveto_gain_item

        Replaces a MuvetoGain document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
