# coding: utf-8

"""
    XENON PMT API

    API for the XENON PMT database  # noqa: E501

    The version of the OpenAPI document: 0.2
    Contact: joe.mosbacher@gmail.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import xepmts
from xepmts.api.muveto_current_change1t_api import MuvetoCurrentChange1tApi  # noqa: E501
from xepmts.rest import ApiException


class TestMuvetoCurrentChange1tApi(unittest.TestCase):
    """MuvetoCurrentChange1tApi unit test stubs"""

    def setUp(self):
        self.api = xepmts.api.muveto_current_change1t_api.MuvetoCurrentChange1tApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_muveto_current_change1t_item(self):
        """Test case for delete_muveto_current_change1t_item

        Deletes a MuvetoCurrentChange1t document  # noqa: E501
        """
        pass

    def test_get_muveto_current_change1t_item(self):
        """Test case for get_muveto_current_change1t_item

        Retrieves a MuvetoCurrentChange1t document  # noqa: E501
        """
        pass

    def test_get_muveto_current_change1ts(self):
        """Test case for get_muveto_current_change1ts

        Retrieves one or more MuvetoCurrentChange1ts  # noqa: E501
        """
        pass

    def test_post_muveto_current_change1ts(self):
        """Test case for post_muveto_current_change1ts

        Stores one or more MuvetoCurrentChange1ts.  # noqa: E501
        """
        pass

    def test_put_muveto_current_change1t_item(self):
        """Test case for put_muveto_current_change1t_item

        Replaces a MuvetoCurrentChange1t document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
