# coding: utf-8

"""
    XENON PMT API

    API for the XENON PMT database  # noqa: E501

    The version of the OpenAPI document: 0.2
    Contact: joe.mosbacher@gmail.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import xepmts
from xepmts.models.muveto_gain import MuvetoGain  # noqa: E501
from xepmts.rest import ApiException

class TestMuvetoGain(unittest.TestCase):
    """MuvetoGain unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MuvetoGain
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = xepmts.models.muveto_gain.MuvetoGain()  # noqa: E501
        if include_optional :
            return MuvetoGain(
                detector = 'muveto', 
                experiment = 'xenonnt', 
                run_id = '0', 
                timestamp = 56, 
                pmt_index = 56, 
                gain = 1.337, 
                gain_err = 1.337, 
                gain_stat_err = 1.337, 
                gain_sys_err = 1.337, 
                voltage = 1.337, 
                occupancy = 1.337, 
                occupancy_err = 1.337, 
                id = '0'
            )
        else :
            return MuvetoGain(
                detector = 'muveto',
                experiment = 'xenonnt',
                pmt_index = 56,
                gain = 1.337,
        )

    def testMuvetoGain(self):
        """Test MuvetoGain"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
