# coding: utf-8

"""
    XENON PMT API

    API for the XENON PMT database  # noqa: E501

    The version of the OpenAPI document: 0.2
    Contact: joe.mosbacher@gmail.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import xepmts
from xepmts.api.muveto_voltage_map_name1t_api import MuvetoVoltageMapName1tApi  # noqa: E501
from xepmts.rest import ApiException


class TestMuvetoVoltageMapName1tApi(unittest.TestCase):
    """MuvetoVoltageMapName1tApi unit test stubs"""

    def setUp(self):
        self.api = xepmts.api.muveto_voltage_map_name1t_api.MuvetoVoltageMapName1tApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_muveto_voltage_map_name1ts(self):
        """Test case for get_muveto_voltage_map_name1ts

        Retrieves one or more MuvetoVoltageMapName1ts  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
