# coding: utf-8

"""
    XENON PMT API

    API for the XENON PMT database  # noqa: E501

    The version of the OpenAPI document: 0.2
    Contact: joe.mosbacher@gmail.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import xepmts
from xepmts.api.muveto_pmt_error1_t_api import MuvetoPmtError1TApi  # noqa: E501
from xepmts.rest import ApiException


class TestMuvetoPmtError1TApi(unittest.TestCase):
    """MuvetoPmtError1TApi unit test stubs"""

    def setUp(self):
        self.api = xepmts.api.muveto_pmt_error1_t_api.MuvetoPmtError1TApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_muveto_pmt_error1_t_item(self):
        """Test case for delete_muveto_pmt_error1_t_item

        Deletes a MuvetoPmtError1T document  # noqa: E501
        """
        pass

    def test_get_muveto_pmt_error1_t_item(self):
        """Test case for get_muveto_pmt_error1_t_item

        Retrieves a MuvetoPmtError1T document  # noqa: E501
        """
        pass

    def test_get_muveto_pmt_errors1_t(self):
        """Test case for get_muveto_pmt_errors1_t

        Retrieves one or more MuvetoPmtErrors1T  # noqa: E501
        """
        pass

    def test_post_muveto_pmt_errors1_t(self):
        """Test case for post_muveto_pmt_errors1_t

        Stores one or more MuvetoPmtErrors1T.  # noqa: E501
        """
        pass

    def test_put_muveto_pmt_error1_t_item(self):
        """Test case for put_muveto_pmt_error1_t_item

        Replaces a MuvetoPmtError1T document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
