# coding: utf-8

"""
    XENON PMT API

    API for the XENON PMT database  # noqa: E501

    The version of the OpenAPI document: 0.2
    Contact: joe.mosbacher@gmail.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import xepmts
from xepmts.models.nveto_voltage_map_name import NvetoVoltageMapName  # noqa: E501
from xepmts.rest import ApiException

class TestNvetoVoltageMapName(unittest.TestCase):
    """NvetoVoltageMapName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test NvetoVoltageMapName
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = xepmts.models.nveto_voltage_map_name.NvetoVoltageMapName()  # noqa: E501
        if include_optional :
            return NvetoVoltageMapName(
                name = '0', 
                experiment = 'xenonnt', 
                detector = 'nveto', 
                id = '0'
            )
        else :
            return NvetoVoltageMapName(
                experiment = 'xenonnt',
                detector = 'nveto',
        )

    def testNvetoVoltageMapName(self):
        """Test NvetoVoltageMapName"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
