[tool.poetry]
name = "duckdb_engine"
version = "0.1.0"
description = ""
authors = ["Elliana <me@mause.me>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
duckdb = "^0.2.1"
sqlalchemy = "^1.3.19"

[tool.poetry.dev-dependencies]
pytest = "^6.1.0"
pre-commit = "^2.7.1"
pdbpp = "^0.10.2"

[tool.poetry.plugins."sqlalchemy.dialects"]
duckdb = "duckdb_engine"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
