[tool.poetry]
name = "jsonschema-default"
version = "1.1.0"
description = "Create default objects from a JSON schema"
authors = ["Martin Boos <mboos@outlook.com>"]
maintainers = ["Martin Boos <mboos@outlook.com>"]
readme = "README.md"
homepage = ""
repository = "https://github.com/mnboos/jsonschema-default"
license = "GNU AGPL v3"

[tool.poetry.dependencies]
python = "^3.7"
xeger = "^0.3.5"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"
jsonschema = "^3.2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
