
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-25T11:24:31+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ab8e9ecd3c93dd2d06c9e45f248afe982f3233c",
 "version": "v0.7.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
