[tool.poetry]
name = "django-gql-framework"
version = "0.1.10"
description = ""
authors = ["Ellis Percival <flyte@failcode.co.uk>"]
license = "MIT"
packages = [
    { include = "graphql_framework" },
]

[tool.poetry.dependencies]
python = "^3.7"
graphql-core = ">=3"
django-guardian = { version = "^2.3.0", optional = true }

[tool.poetry.dev-dependencies]
rope = "^0.17.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
