# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hydro_serving_grpc/vis/api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hydro_serving_grpc/vis/api.proto',
  package='hydrosphere.vis',
  syntax='proto3',
  serialized_pb=_b('\n hydro_serving_grpc/vis/api.proto\x12\x0fhydrosphere.vis\x1a\x1bgoogle/protobuf/empty.proto\"C\n\x0cRefitRequest\x12\x18\n\x10model_version_id\x18\x01 \x01(\x03\x12\x19\n\x11refit_transformer\x18\x02 \x01(\x08\x32S\n\nVisService\x12\x45\n\nRefitModel\x12\x1d.hydrosphere.vis.RefitRequest\x1a\x16.google.protobuf.Empty\"\x00\x42\x1c\n\x1aio.hydrosphere.serving.visb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_REFITREQUEST = _descriptor.Descriptor(
  name='RefitRequest',
  full_name='hydrosphere.vis.RefitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_version_id', full_name='hydrosphere.vis.RefitRequest.model_version_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='refit_transformer', full_name='hydrosphere.vis.RefitRequest.refit_transformer', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=149,
)

DESCRIPTOR.message_types_by_name['RefitRequest'] = _REFITREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RefitRequest = _reflection.GeneratedProtocolMessageType('RefitRequest', (_message.Message,), dict(
  DESCRIPTOR = _REFITREQUEST,
  __module__ = 'hydro_serving_grpc.vis.api_pb2'
  # @@protoc_insertion_point(class_scope:hydrosphere.vis.RefitRequest)
  ))
_sym_db.RegisterMessage(RefitRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032io.hydrosphere.serving.vis'))

_VISSERVICE = _descriptor.ServiceDescriptor(
  name='VisService',
  full_name='hydrosphere.vis.VisService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=151,
  serialized_end=234,
  methods=[
  _descriptor.MethodDescriptor(
    name='RefitModel',
    full_name='hydrosphere.vis.VisService.RefitModel',
    index=0,
    containing_service=None,
    input_type=_REFITREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VISSERVICE)

DESCRIPTOR.services_by_name['VisService'] = _VISSERVICE

# @@protoc_insertion_point(module_scope)
