[package]
name = "tantivy"
version = "0.13.1-rc.1"
readme = "README.md"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "MIT"

[lib]
name = "tantivy"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.15"
tantivy = "0.13.1"
itertools = "0.9.0"
futures = "0.3.5"

[dependencies.pyo3]
version = "0.12.1"
features = ["extension-module"]

[package.metadata.maturin]
requires-python = ">=3.7"
project-url = ["https://github.com/tantivy-search/tantivy-py"]
