- project:
    check:
      jobs:
        - thoth-coala
    gate:
      jobs:
        - thoth-coala
    post:
      jobs:
        - "trigger-build":
            vars:
              cluster: paas.psi.redhat.com
              namespace: aicoe-prod-bots
              buildConfigName: kebechet-job
    release:
      jobs:
        - upload-pypi-sesheta
    kebechet-auto-gate:
      jobs:
        - thoth-coala
