# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vda/grpc/dn_agent.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vda/grpc/dn_agent.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17vda/grpc/dn_agent.proto\"9\n\x10\x44nAgentReplyInfo\x12\x12\n\nreply_code\x18\x01 \x01(\x04\x12\x11\n\treply_msg\x18\x02 \x01(\t\"D\n\x0cVdBackendCfg\x12\r\n\x05vd_id\x18\x01 \x01(\t\x12\x13\n\x0bvd_clusters\x18\x02 \x01(\x04\x12\x10\n\x08\x63ntlr_id\x18\x03 \x01(\t\"K\n\x05PdCfg\x12\r\n\x05pd_id\x18\x01 \x01(\t\x12\x0f\n\x07pd_conf\x18\x02 \x01(\t\x12\"\n\x0bvd_cfg_list\x18\x03 \x03(\x0b\x32\r.VdBackendCfg\"D\n\x05\x44nCfg\x12\r\n\x05\x64n_id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x04\x12\x1b\n\x0bpd_cfg_list\x18\x04 \x03(\x0b\x32\x06.PdCfg\"9\n\x0fSyncupDnRequest\x12\x0e\n\x06req_id\x18\x01 \x01(\t\x12\x16\n\x06\x64n_cfg\x18\x02 \x01(\x0b\x32\x06.DnCfg\"@\n\rVdBackendInfo\x12\r\n\x05vd_id\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\x08\x12\x11\n\terror_msg\x18\x03 \x01(\t\"\x8e\x01\n\x06PdInfo\x12\r\n\x05pd_id\x18\x01 \x01(\t\x12\x16\n\x0etotal_clusters\x18\x02 \x01(\x04\x12\x15\n\rfree_clusters\x18\x03 \x01(\x04\x12\r\n\x05\x65rror\x18\x04 \x01(\x08\x12\x11\n\terror_msg\x18\x05 \x01(\t\x12$\n\x0cvd_info_list\x18\x06 \x03(\x0b\x32\x0e.VdBackendInfo\"X\n\x06\x44nInfo\x12\r\n\x05\x64n_id\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\x08\x12\x11\n\terror_msg\x18\x03 \x01(\t\x12\x1d\n\x0cpd_info_list\x18\x04 \x03(\x0b\x32\x07.PdInfo\"P\n\rSyncupDnReply\x12%\n\nreply_info\x18\x01 \x01(\x0b\x32\x11.DnAgentReplyInfo\x12\x18\n\x07\x64n_info\x18\x02 \x01(\x0b\x32\x07.DnInfo\"3\n\x12\x44nHeartbeatRequest\x12\x0e\n\x06req_id\x18\x01 \x01(\t\x12\r\n\x05\x64n_id\x18\x02 \x01(\t\"9\n\x10\x44nHeartbeatReply\x12%\n\nreply_info\x18\x01 \x01(\x0b\x32\x11.DnAgentReplyInfo2r\n\x07\x44nAgent\x12.\n\x08SyncupDn\x12\x10.SyncupDnRequest\x1a\x0e.SyncupDnReply\"\x00\x12\x37\n\x0b\x44nHeartbeat\x12\x13.DnHeartbeatRequest\x1a\x11.DnHeartbeatReply\"\x00\x62\x06proto3'
)




_DNAGENTREPLYINFO = _descriptor.Descriptor(
  name='DnAgentReplyInfo',
  full_name='DnAgentReplyInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply_code', full_name='DnAgentReplyInfo.reply_code', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reply_msg', full_name='DnAgentReplyInfo.reply_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=84,
)


_VDBACKENDCFG = _descriptor.Descriptor(
  name='VdBackendCfg',
  full_name='VdBackendCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vd_id', full_name='VdBackendCfg.vd_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vd_clusters', full_name='VdBackendCfg.vd_clusters', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cntlr_id', full_name='VdBackendCfg.cntlr_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=154,
)


_PDCFG = _descriptor.Descriptor(
  name='PdCfg',
  full_name='PdCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pd_id', full_name='PdCfg.pd_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pd_conf', full_name='PdCfg.pd_conf', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vd_cfg_list', full_name='PdCfg.vd_cfg_list', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=231,
)


_DNCFG = _descriptor.Descriptor(
  name='DnCfg',
  full_name='DnCfg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dn_id', full_name='DnCfg.dn_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='DnCfg.version', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pd_cfg_list', full_name='DnCfg.pd_cfg_list', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=301,
)


_SYNCUPDNREQUEST = _descriptor.Descriptor(
  name='SyncupDnRequest',
  full_name='SyncupDnRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_id', full_name='SyncupDnRequest.req_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dn_cfg', full_name='SyncupDnRequest.dn_cfg', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=360,
)


_VDBACKENDINFO = _descriptor.Descriptor(
  name='VdBackendInfo',
  full_name='VdBackendInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vd_id', full_name='VdBackendInfo.vd_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='VdBackendInfo.error', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_msg', full_name='VdBackendInfo.error_msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=426,
)


_PDINFO = _descriptor.Descriptor(
  name='PdInfo',
  full_name='PdInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pd_id', full_name='PdInfo.pd_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_clusters', full_name='PdInfo.total_clusters', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='free_clusters', full_name='PdInfo.free_clusters', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='PdInfo.error', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_msg', full_name='PdInfo.error_msg', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vd_info_list', full_name='PdInfo.vd_info_list', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=429,
  serialized_end=571,
)


_DNINFO = _descriptor.Descriptor(
  name='DnInfo',
  full_name='DnInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dn_id', full_name='DnInfo.dn_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='DnInfo.error', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_msg', full_name='DnInfo.error_msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pd_info_list', full_name='DnInfo.pd_info_list', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=573,
  serialized_end=661,
)


_SYNCUPDNREPLY = _descriptor.Descriptor(
  name='SyncupDnReply',
  full_name='SyncupDnReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply_info', full_name='SyncupDnReply.reply_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dn_info', full_name='SyncupDnReply.dn_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=663,
  serialized_end=743,
)


_DNHEARTBEATREQUEST = _descriptor.Descriptor(
  name='DnHeartbeatRequest',
  full_name='DnHeartbeatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='req_id', full_name='DnHeartbeatRequest.req_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dn_id', full_name='DnHeartbeatRequest.dn_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=745,
  serialized_end=796,
)


_DNHEARTBEATREPLY = _descriptor.Descriptor(
  name='DnHeartbeatReply',
  full_name='DnHeartbeatReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply_info', full_name='DnHeartbeatReply.reply_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=798,
  serialized_end=855,
)

_PDCFG.fields_by_name['vd_cfg_list'].message_type = _VDBACKENDCFG
_DNCFG.fields_by_name['pd_cfg_list'].message_type = _PDCFG
_SYNCUPDNREQUEST.fields_by_name['dn_cfg'].message_type = _DNCFG
_PDINFO.fields_by_name['vd_info_list'].message_type = _VDBACKENDINFO
_DNINFO.fields_by_name['pd_info_list'].message_type = _PDINFO
_SYNCUPDNREPLY.fields_by_name['reply_info'].message_type = _DNAGENTREPLYINFO
_SYNCUPDNREPLY.fields_by_name['dn_info'].message_type = _DNINFO
_DNHEARTBEATREPLY.fields_by_name['reply_info'].message_type = _DNAGENTREPLYINFO
DESCRIPTOR.message_types_by_name['DnAgentReplyInfo'] = _DNAGENTREPLYINFO
DESCRIPTOR.message_types_by_name['VdBackendCfg'] = _VDBACKENDCFG
DESCRIPTOR.message_types_by_name['PdCfg'] = _PDCFG
DESCRIPTOR.message_types_by_name['DnCfg'] = _DNCFG
DESCRIPTOR.message_types_by_name['SyncupDnRequest'] = _SYNCUPDNREQUEST
DESCRIPTOR.message_types_by_name['VdBackendInfo'] = _VDBACKENDINFO
DESCRIPTOR.message_types_by_name['PdInfo'] = _PDINFO
DESCRIPTOR.message_types_by_name['DnInfo'] = _DNINFO
DESCRIPTOR.message_types_by_name['SyncupDnReply'] = _SYNCUPDNREPLY
DESCRIPTOR.message_types_by_name['DnHeartbeatRequest'] = _DNHEARTBEATREQUEST
DESCRIPTOR.message_types_by_name['DnHeartbeatReply'] = _DNHEARTBEATREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DnAgentReplyInfo = _reflection.GeneratedProtocolMessageType('DnAgentReplyInfo', (_message.Message,), {
  'DESCRIPTOR' : _DNAGENTREPLYINFO,
  '__module__' : 'vda.grpc.dn_agent_pb2'
  # @@protoc_insertion_point(class_scope:DnAgentReplyInfo)
  })
_sym_db.RegisterMessage(DnAgentReplyInfo)

VdBackendCfg = _reflection.GeneratedProtocolMessageType('VdBackendCfg', (_message.Message,), {
  'DESCRIPTOR' : _VDBACKENDCFG,
  '__module__' : 'vda.grpc.dn_agent_pb2'
  # @@protoc_insertion_point(class_scope:VdBackendCfg)
  })
_sym_db.RegisterMessage(VdBackendCfg)

PdCfg = _reflection.GeneratedProtocolMessageType('PdCfg', (_message.Message,), {
  'DESCRIPTOR' : _PDCFG,
  '__module__' : 'vda.grpc.dn_agent_pb2'
  # @@protoc_insertion_point(class_scope:PdCfg)
  })
_sym_db.RegisterMessage(PdCfg)

DnCfg = _reflection.GeneratedProtocolMessageType('DnCfg', (_message.Message,), {
  'DESCRIPTOR' : _DNCFG,
  '__module__' : 'vda.grpc.dn_agent_pb2'
  # @@protoc_insertion_point(class_scope:DnCfg)
  })
_sym_db.RegisterMessage(DnCfg)

SyncupDnRequest = _reflection.GeneratedProtocolMessageType('SyncupDnRequest', (_message.Message,), {
  'DESCRIPTOR' : _SYNCUPDNREQUEST,
  '__module__' : 'vda.grpc.dn_agent_pb2'
  # @@protoc_insertion_point(class_scope:SyncupDnRequest)
  })
_sym_db.RegisterMessage(SyncupDnRequest)

VdBackendInfo = _reflection.GeneratedProtocolMessageType('VdBackendInfo', (_message.Message,), {
  'DESCRIPTOR' : _VDBACKENDINFO,
  '__module__' : 'vda.grpc.dn_agent_pb2'
  # @@protoc_insertion_point(class_scope:VdBackendInfo)
  })
_sym_db.RegisterMessage(VdBackendInfo)

PdInfo = _reflection.GeneratedProtocolMessageType('PdInfo', (_message.Message,), {
  'DESCRIPTOR' : _PDINFO,
  '__module__' : 'vda.grpc.dn_agent_pb2'
  # @@protoc_insertion_point(class_scope:PdInfo)
  })
_sym_db.RegisterMessage(PdInfo)

DnInfo = _reflection.GeneratedProtocolMessageType('DnInfo', (_message.Message,), {
  'DESCRIPTOR' : _DNINFO,
  '__module__' : 'vda.grpc.dn_agent_pb2'
  # @@protoc_insertion_point(class_scope:DnInfo)
  })
_sym_db.RegisterMessage(DnInfo)

SyncupDnReply = _reflection.GeneratedProtocolMessageType('SyncupDnReply', (_message.Message,), {
  'DESCRIPTOR' : _SYNCUPDNREPLY,
  '__module__' : 'vda.grpc.dn_agent_pb2'
  # @@protoc_insertion_point(class_scope:SyncupDnReply)
  })
_sym_db.RegisterMessage(SyncupDnReply)

DnHeartbeatRequest = _reflection.GeneratedProtocolMessageType('DnHeartbeatRequest', (_message.Message,), {
  'DESCRIPTOR' : _DNHEARTBEATREQUEST,
  '__module__' : 'vda.grpc.dn_agent_pb2'
  # @@protoc_insertion_point(class_scope:DnHeartbeatRequest)
  })
_sym_db.RegisterMessage(DnHeartbeatRequest)

DnHeartbeatReply = _reflection.GeneratedProtocolMessageType('DnHeartbeatReply', (_message.Message,), {
  'DESCRIPTOR' : _DNHEARTBEATREPLY,
  '__module__' : 'vda.grpc.dn_agent_pb2'
  # @@protoc_insertion_point(class_scope:DnHeartbeatReply)
  })
_sym_db.RegisterMessage(DnHeartbeatReply)



_DNAGENT = _descriptor.ServiceDescriptor(
  name='DnAgent',
  full_name='DnAgent',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=857,
  serialized_end=971,
  methods=[
  _descriptor.MethodDescriptor(
    name='SyncupDn',
    full_name='DnAgent.SyncupDn',
    index=0,
    containing_service=None,
    input_type=_SYNCUPDNREQUEST,
    output_type=_SYNCUPDNREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DnHeartbeat',
    full_name='DnAgent.DnHeartbeat',
    index=1,
    containing_service=None,
    input_type=_DNHEARTBEATREQUEST,
    output_type=_DNHEARTBEATREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DNAGENT)

DESCRIPTOR.services_by_name['DnAgent'] = _DNAGENT

# @@protoc_insertion_point(module_scope)
