
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-21T11:46:38-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "46a5489fb9cdda95bda595bd6d60d9065df31a50",
 "version": "0.8.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
