[tool.poetry]
name = "notalib"
version = "1.0.1"
description = ""
authors = ["m1kc (Max Musatov) <m1kc@yandex.ru>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
arrow = ">=0.14.0"

[tool.poetry.dev-dependencies]
django = "^2.2"
pytest = "^5.0"
pytest-cov = "^2.7"
hypothesis = "^4.32"
hypothesis-django = "^2.0"
hypothesis-numpy = "^2.0"
flake8 = "^3.7"
pytest-django = "^3.10.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
