augs:
  LR: 0.5
  UD: 0.0
  brightness: 0.25
  contrast: 0.1
  crop_size: null
  degrees: 10
  normalization:
    N: 29675865600
    mean:
    - 0.39263111139845663
    - 0.3842978096514951
    - 0.35869140752306883
    std:
    - 0.25925379864572906
    - 0.2532715296559611
    - 0.25239786007408804
  pad: null
  random_resize: false
  resize:
  - 224
  - 224
compute:
  batch_size: 16
  distributed: false
  gpu_id: 0
  num_workers: 8
project:
  class_names:
  - background
  - BaseballPitch
  - BasketballDunk
  - Billiards
  - CleanAndJerk
  - CliffDiving
  - CricketBowling
  - CricketShot
  - Diving
  - FrisbeeCatch
  - GolfSwing
  - HammerThrow
  - HighJump
  - JavelinThrow
  - LongJump
  - PoleVault
  - Shotput
  - SoccerPenalty
  - TennisSwing
  - ThrowDiscus
  - VolleyballSpiking
  config_file: /media/jim/FAST/DATA/deepethogram_testing_thumos14/project_config.yaml
  data_path: DATA
  labeler: null
  model_path: models
  name: thumos14
  path: /media/jim/FAST/DATA/deepethogram_testing_thumos14
sequence:
  filter_length: 15
split:
  file: null
  reload: true
train:
  loss_weight_exp: 1.0
preset: deg_f
