[tool.poetry]
name = "task"
version = "0.1.1"
description = "Task cli tool"
authors = ["matteyeux"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.2"
click-default-group = "^1.2.2"
python-dateutil = "^2.8.1"
tabulate = "^0.8.7"

[tool.poetry.dev-dependencies]
pre-commit = "^2.7.1"
flake8 = "^3.8.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
