[tool.poetry]
name = "autogram-commons"
version = "0.2.1"
description = ""
authors = ["Joscha Götzer <joscha.goetzer@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = {extras = ["dotenv"], version = "^1.6.1"}
"ruamel.yaml" = "^0.16.12"

[tool.poetry.dev-dependencies]
black = {version = ">=20.8b1", python = "^3.8", markers = "platform_python_implementation == 'CPython'"}
mypy = ">0.770"
birdseye = "^0.8.3"
mkinit = "^0.2.0"
typer = "^0.3.1"
pytest = "*"
pytest-asyncio = "*"
pyrogram = "1.*"
pytest-cov = "^2.10.1"
pre-commit = "^2.7.1"
devtools = {extras = ["pygments"], version = "^0.6"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
