
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-22T11:56:47-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "3cdd12fcc58b1042bd2a0590137a3082c49e7b73",
 "version": "0.0.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
