from google.ads.google_ads.v4.proto.services import conversion_upload_service_pb2 as conversion_upload_service_pb2
from google.ads.google_ads.v4.services import conversion_upload_service_client_config as conversion_upload_service_client_config
from google.ads.google_ads.v4.services.transports import conversion_upload_service_grpc_transport as conversion_upload_service_grpc_transport
from google.oauth2 import service_account as service_account
import grpc  # type: ignore
from google.ads.google_ads.v4.services.transports.conversion_upload_service_grpc_transport import ConversionUploadServiceGrpcTransport
from google.auth.credentials import Credentials  # type: ignore
from google.api_core.gapic_v1.client_info import ClientInfo  # type: ignore
from google.api_core.retry import Retry  # type: ignore
from typing import Optional, Dict, Any, List, Sequence, Tuple, Union, Callable, ClassVar

class ConversionUploadServiceClient:
    SERVICE_ADDRESS: ClassVar[str] = ...
    @classmethod
    def from_service_account_file(cls, filename: str, *args: Any, **kwargs: Any) -> ConversionUploadServiceClient: ...
    @classmethod
    def from_service_account_json(cls, filename: str, *args: Any, **kwargs: Any) -> ConversionUploadServiceClient: ...
    transport: Union[ConversionUploadServiceGrpcTransport, Callable[[Credentials, type], ConversionUploadServiceGrpcTransport]] = ...
    def __init__(self, transport: Optional[Union[ConversionUploadServiceGrpcTransport, Callable[[Credentials, type], ConversionUploadServiceGrpcTransport]]] = ..., channel: Optional[grpc.Channel] = ..., credentials: Optional[Credentials] = ..., client_config: Optional[Dict[str, Any]] = ..., client_info: Optional[ClientInfo] = ...) -> None: ...
    def upload_click_conversions(self, customer_id: Any, conversions: Any, partial_failure: Optional[Any] = ..., validate_only: Optional[Any] = ..., retry: Any = ..., timeout: Any = ..., metadata: Optional[Any] = ...): ...
    def upload_call_conversions(self, customer_id: Any, conversions: Any, partial_failure: Optional[Any] = ..., validate_only: Optional[Any] = ..., retry: Any = ..., timeout: Any = ..., metadata: Optional[Any] = ...): ...
