from google.ads.google_ads.v4.proto.services import google_ads_service_pb2 as google_ads_service_pb2
from google.ads.google_ads.v4.services import google_ads_service_client_config as google_ads_service_client_config
from google.ads.google_ads.v4.services.transports import google_ads_service_grpc_transport as google_ads_service_grpc_transport
from google.oauth2 import service_account as service_account
import grpc  # type: ignore
from google.ads.google_ads.v4.services.transports.google_ads_service_grpc_transport import GoogleAdsServiceGrpcTransport
from google.auth.credentials import Credentials  # type: ignore
from google.api_core.gapic_v1.client_info import ClientInfo  # type: ignore
from google.api_core.retry import Retry  # type: ignore
from typing import Optional, Dict, Any, List, Sequence, Tuple, Union, Callable, ClassVar

class GoogleAdsServiceClient:
    SERVICE_ADDRESS: ClassVar[str] = ...
    @classmethod
    def from_service_account_file(cls, filename: str, *args: Any, **kwargs: Any) -> GoogleAdsServiceClient: ...
    @classmethod
    def from_service_account_json(cls, filename: str, *args: Any, **kwargs: Any) -> GoogleAdsServiceClient: ...
    transport: Union[GoogleAdsServiceGrpcTransport, Callable[[Credentials, type], GoogleAdsServiceGrpcTransport]] = ...
    def __init__(self, transport: Optional[Union[GoogleAdsServiceGrpcTransport, Callable[[Credentials, type], GoogleAdsServiceGrpcTransport]]] = ..., channel: Optional[grpc.Channel] = ..., credentials: Optional[Credentials] = ..., client_config: Optional[Dict[str, Any]] = ..., client_info: Optional[ClientInfo] = ...) -> None: ...
    def search(self, customer_id: Any, query: Any, page_size: Optional[Any] = ..., validate_only: Optional[Any] = ..., return_total_results_count: Optional[Any] = ..., summary_row_setting: Optional[Any] = ..., retry: Any = ..., timeout: Any = ..., metadata: Optional[Any] = ...): ...
    def search_stream(self, customer_id: Any, query: Any, summary_row_setting: Optional[Any] = ..., retry: Any = ..., timeout: Any = ..., metadata: Optional[Any] = ...): ...
    def mutate(self, customer_id: Any, mutate_operations: Any, partial_failure: Optional[Any] = ..., validate_only: Optional[Any] = ..., retry: Any = ..., timeout: Any = ..., metadata: Optional[Any] = ...): ...
