
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-20T10:44:51+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "41a183ca4da61cc1ad78e8d24041e0e94046a401",
 "version": "v0.3.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
