'''
Created on 2019年3月6日

@author: 67362
'''


class jumalocator(object):
    locator_menu_div = "xpath=.//*[@id='c-layout-left']"
    current_ivudropdowntransfer = "xpath=.//*[contains(@class,'ivu-dropdown-transfer') and not(contains(@style,'display: none'))]"
    all_ivudropdowntransfer_css = "ivu-dropdown-transfer"
    current_context_menu = "xpath=.//*[contains(@id,'context-menu') and not(contains(@style,'display: none'))]"
    all_context_menu = "c-context-menu"
    parent_tenant = "xpath=.//*[@id='c-layout-head']/div[2]/div/ul/li[1]/div/div[1]"
    child_tenant = "xpath=.//*[@id='c-layout-head']/div[2]/div/ul/li[2]/div/div[1]"
    current_ivuselectdropdowntransfer = "xpath=.//*[contains(@class,'ivu-select-dropdown-transfer') and not(contains(@style,'display: none'))]"
    all_ivuselectdropdowntransfer_css = "ivu-select-dropdown-transfer"
    loadding_spin = "css=.c-spin.fade-leave-active"
    table_headers = "xpath=.//div[@id='c-layout-right']//div[contains(@class,'ivu-table-header')]"
    table_bodys = "xpath=.//div[@id='c-layout-right']//div[contains(@class,'ivu-table-body')]"
    table_trips = "xpath=.//div[@id='c-layout-right']//div[contains(@class,'ivu-table-trip')]"
    current_table_loading = "xpath=.//*[contains(@class,'ivu-spin-show-text') and descendant::i[contains(@class,'table-loading')]]"
    current_modal_btn_for_text = "xpath=.//button[ancestor::*[@class='ivu-modal' and not(contains(@style,'display: none'))] and descendant::span[text()='"
    current_message_info = "xpath=.//div[@class='ivu-message']//span"
    current_menu_text = "xpath=.//a[contains(@class,'menu-text') and contains(@class,'current')]"
    auto_list = "xpath=.//*[@class='ivu-modal' and not(contains(@style,'display: none'))]//following-sibling::*//div[contains(@id,'auto-complete-list')]"
    auto_list_active = "xpath=.//div[contains(@class,'slide-up-enter-active') and not(contains(@style,'display: none'))]"
    auto_list_select = "xpath=.//*[@data-wrapper-id='"
    auto_list_select_tailstr = "']//a["
    date_picker_css = "ivu-date-picker-transfer"
    loc_date_picker = "css=.ivu-date-picker-transfer:not([style*='display: none'])"
    select_year = "xpath=.//*[contains(@class,'ivu-date-picker-transfer') and not(contains(@style,'display: none'))]//span[child::*[contains(@class,'ivu-date-picker-header-label')]]/span[1]"
    select_month = "xpath=.//*[contains(@class,'ivu-date-picker-transfer') and not(contains(@style,'display: none'))]//span[child::*[contains(@class,'ivu-date-picker-header-label')]]/span[2]"
    year_first_cell = "xpath=.//*[contains(@class,'ivu-date-picker-transfer') and not(contains(@style,'display: none'))]//div[contains(@class,'ivu-date-picker-cells-year')]/span[1]"
    year_last_cell = "xpath=.//*[contains(@class,'ivu-date-picker-transfer') and not(contains(@style,'display: none'))]//div[contains(@class,'ivu-date-picker-cells-year')]/span[last()]"
    year_to_select_cell = "xpath=.//*[contains(@class,'ivu-date-picker-transfer') and not(contains(@style,'display: none'))]//div[contains(@class,'ivu-date-picker-cells-year')]/span[descendant::text()='"
    month_to_select_cell = "xpath=.//*[contains(@class,'ivu-date-picker-transfer') and not(contains(@style,'display: none'))]//div[contains(@class,'ivu-date-picker-cells-month')]/span["
    day_to_select_cell = "xpath=.//*[contains(@class,'ivu-date-picker-transfer') and not(contains(@style,'display: none'))]//div[contains(@class,'ivu-picker-panel-content')]/div[1]/span[contains(@class,'ivu-date-picker-cells-cell') and not(contains(@class,'ivu-date-picker-cells-cell-prev-month')) and descendant::*[text()='"
    prev_btn_arrow_double = "xpath=.//*[contains(@class,'ivu-date-picker-transfer') and not(contains(@style,'display: none'))]//span[contains(@class,'ivu-date-picker-prev-btn') and contains(@class,'ivu-date-picker-prev-btn-arrow-double')]"
    next_btn_arrow_double = "xpath=.//*[contains(@class,'ivu-date-picker-transfer') and not(contains(@style,'display: none'))]//span[contains(@class,'ivu-date-picker-next-btn') and contains(@class,'ivu-date-picker-next-btn-arrow-double')]"
    prev_btn_arrow = "xpath=.//*[contains(@class,'ivu-date-picker-transfer') and not(contains(@style,'display: none'))]//span[contains(@class,'ivu-date-picker-prev-btn') and contains(@class,'ivu-date-picker-prev-btn-arrow') and not(contains(@class,'ivu-date-picker-prev-btn-arrow-double'))]"
    next_btn_arrow = "xpath=.//*[contains(@class,'ivu-date-picker-transfer') and not(contains(@style,'display: none'))]//span[contains(@class,'ivu-date-picker-next-btn') and contains(@class,'ivu-date-picker-next-btn-arrow') and not(contains(@class,'ivu-date-picker-next-btn-arrow-double'))]"
    select_attachfile_btn = "xpath=.//*[@class='ivu-modal' and not(contains(@style,'display: none'))]//*[contains(@id,'upload-container')]//div[@class='btn-group']/button[descendant::text()='选择文件']"
    loc_attach_files_status = "xpath=.//*[@class='ivu-modal' and not(contains(@style,'display: none'))]//*[contains(@id,'upload-container')]//*[contains(@class,'progress-info')]"
    locator_tabs_tab_1 = "xpath=.//*[contains(@class,'ivu-tabs-bar')]//*[contains(@class,'ivu-tabs-tab') and contains(text(),'"
    locator_tabs_tab_2 = "')]"
    first_row_operate_left = "xpath=.//tr[1]/td[contains(@class,'operation-cell')]//div[contains(@class,'c-table-btn')]/span[1]//a"
    first_row_operate_right = "xpath=.//tr[1]/td[contains(@class,'operation-cell')]//div[contains(@class,'c-table-btn')]/span[2]//a"
    loc_current_modal_mask = "css=.ivu-modal-mask:not([style*='display: none'])"
    loc_current_modal_warp = "css=.ivu-modal-wrap:not(.ivu-modal-hidden)"
    loc_current_modal_mask_xpath = "xpath=.//*[contains(@class,'ivu-modal-mask') and not(contains(@style,'display: none')) and contains(@class,'fade-enter-active')]"
    loc_current_modal_mask_text_path_2 = "xpath=.//*[contains(@class,'ivu-modal-mask') and not(contains(@style,'display: none')) and contains(@class,'fade-enter-active') and following-sibling::div[@class='ivu-modal-wrap' and not(contains(@style,'display: none')) and descendant::text()='"
    loc_current_modal_mask_text_path = "xpath=.//*[contains(@class,'ivu-modal-mask') and not(contains(@style,'display: none')) and following-sibling::div[@class='ivu-modal-wrap' and not(contains(@style,'display: none')) and descendant::text()='"
    loc_current_modal_warp_xpath = "xpath=.//*[contains(@class,'ivu-modal-wrap') and not(contains(@style,'display: none')) and descendant::*[contains(@class,'ivu-modal-header') and descendant::text()='"
    loc_table_resultnum = "css=.page-total"
    loc_checkbox = "xpath=.//label"
    loc_checkbox_group = "xpath=.//*[contains(@id,'modal') and not(contains(@style,'display: none'))]//div[@class='ivu-checkbox-group']"
    loc_checkbox_select_str = "]/label[descendant::input[@type='checkbox']]"
    loc_cascader_transfer = "xpath=.//*[contains(@class,'ivu-cascader-transfer')]/div/span/ul[@class='ivu-cascader-menu']"
    loc_cascader_transfer2 = "xpath=.//li[contains(text(),'"
    loc_cascader_transfer3 = "')]"
    loc_cascader_transfer4 = "xpath=.//following-sibling::span/ul"
    all_cascader_transfer_css = "ivu-cascader-transfer"
    loc_current_cascader_transfer = "css=.ivu-cascader-transfer:not([style*='display: none'])"
    slide_up_active = "slide-up-enter-active"
    loc_ivu_table_body = "css=.ivu-table-body"
    loc_ivu_table_tip = "css=.ivu-table-tip"
    loc_find_auto_complete_list = "xpath=.//ancestor::div[contains(@id,'auto-complete-list')][1] | descendant::div[contains(@id,'auto-complete-list')][1]"
    loc_spread_btn = "xpath=.//button[contains(@class,'ivu-btn') and descendant::span[contains(text(),'展开') or contains(text(),'收起')]]"
    loc_file_attach_upload_save = "xpath=.//*[contains(@class,'ivu-modal-wrap') and not(contains(@class,'ivu-modal-hidden'))]//*[contains(@class,'ivu-modal-header') and descendant::text()='上传附件']/following-sibling::div[contains(@class,'ivu-modal-footer')]//button[2]"
    loc_select_export_fields = "css=.define-export-con .fields-item"
    loc_export = "xpath=.//button[contains(@class,'ivu-btn') and descendant::span[contains(text(),'导出')]]"
    loc_modal_button_find = "xpath=.//*[contains(@class,'ivu-modal-footer') or contains(@class,'ivu-modal-confirm-footer')]//button[descendant::*[contains(text(),'"
    loc_modal_body_button_find = "xpath=.//*[contains(@class,'ivu-modal-body') or contains(@class,'ivu-modal-confirm-body')]//button[descendant::*[contains(text(),'"
    loc_treeWithContextMenu_div = "xpath=.//*[contains(@id,'treeWithContextMenu')]/div"
    loc_c_pop_menu_btn = "xpath=.//*[@class='c-pop-menu']//button[descendant::*[contains(text(),'"
    loc_c_pop_menu_btn2 = "')]]"
    loc_editableTable_item_input = "xpath=.//*[contains(@id,'editableTable')]//*[contains(@class,'c-editable-table-tbody')]//tbody/tr["
    loc_editableTable_item_input2 = "]/td["
    loc_editableTable_item_input3 = "]//input"
    loc_editableTable_item_save = "]/td[last()]//a[text()='保存']"
    loc_table_select_all = "xpath=.//div[@id='c-layout-right']//div[contains(@class,'ivu-table-header')]["
    loc_table_select_all_2 = "]//tr[1]/th[1]//input[@type='checkbox']/parent::span"
    loc_table_select_index = "xpath=.//div[@id='c-layout-right']//div[contains(@class,'ivu-table-body')]["
    loc_table_select_index2 = "]//tr["
    loc_table_select_index3 = "]/td[1]//input[@type='checkbox']/parent::span"
    loc_table_select_index_all = "]//tr/td[1]//input[@type='checkbox']/parent::span"
    loc_auto_complete_close = "xpath=./parent::*/i[contains(@class,'ivu-icon-close-circled')]"
    status_search = "xpath=.//*[contains(@class,'cols-wrapper')]//label[text()='跟进阶段']/following-sibling::div//li[normalize-space(text())='"
    status_search_loctail = "']"
    status_search_text2 = "xpath=.//*[contains(@class,'cols-wrapper')]//label[text()='跟进阶段']/following-sibling::div//li"
    status_search_text = "xpath=.//*[contains(@class,'cols-wrapper')]//label[text()='跟进阶段']/following-sibling::div//li[contains(@class,'active')]"
