[tool.poetry]
name = "BssApi-DbfRead"
version = "0.1.0"
description = ""
authors = ["Anton Rastyazhenko <rastyazhenko.anton@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^6.0.2"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
