[tool.poetry]
name = "questionbuilder"
version = "1.1.13"
description = "Wordbox. Question builder package"
authors = ["Cesar Juarez <cesar@wordbox.ai>"]
packages = [
    { include = "question_builder" }
]

[tool.poetry.dependencies]
python = "^3.8"
neo4j = "1.7.6"
setuptools = "^50.3.0"
wheel = "^0.35.1"
editdistance = "^0.5.3"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
coverage = "^5.2.1"
flake8 = "^3.8.3"
mypy = "^0.782"
pre-commit = "^2.7.1"
black = "^20.8b1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
