repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
    -   id: isort
        additional_dependencies: [toml]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: check-ast
    -   id: check-docstring-first
    -   id: check-case-conflict
    -   id: check-yaml
    -   id: check-toml
    -   id: debug-statements
    -   id: requirements-txt-fixer
