
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-29T10:55:08+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "3044ee75faff422f67e6aa3443979f1c924b1b1a",
 "version": "2.9.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
