[tool.poetry]
name = "splunk_add_on_ucc_framework"
version = "4.0.5a6"
description = "Splunk Add-on SDK formerly UCC is a build and code generation framework"
authors = ["rfaircloth-splunk <rfaircloth@splunk.com>"]
exclude = [
    "build.py",
    "splunk_add_on_ucc_framework/UCC-UI-lib/bower_components",
    "splunk_add_on_ucc_framework/UCC-UI-lib/config",
    "splunk_add_on_ucc_framework/UCC-UI-lib/node_modules",
    "splunk_add_on_ucc_framework/UCC-UI-lib/testes"
    ]
include = [
"splunk_add_on_ucc_framework/package/appserver/static/css/bootstrap-enterprise.css",
"splunk_add_on_ucc_framework/package/appserver/static/css/bootstrap-lite.css",
"splunk_add_on_ucc_framework/package/appserver/static/css/common.css",
"splunk_add_on_ucc_framework/package/appserver/static/css/configuration.css",
"splunk_add_on_ucc_framework/package/appserver/static/css/createInput.css",
"splunk_add_on_ucc_framework/package/appserver/static/css/inputs.css",
"splunk_add_on_ucc_framework/package/appserver/static/css/switchButton.css",
"splunk_add_on_ucc_framework/package/appserver/static/js/build/1.1.js",
"splunk_add_on_ucc_framework/package/appserver/static/js/build/2.2.js",
"splunk_add_on_ucc_framework/package/appserver/static/js/build/3.3.js",
"splunk_add_on_ucc_framework/package/appserver/static/js/build/4.4.js",
"splunk_add_on_ucc_framework/package/appserver/static/js/build/5.5.js",
"splunk_add_on_ucc_framework/package/appserver/static/js/build/common.js",
"splunk_add_on_ucc_framework/package/appserver/static/js/build/entry_page.js",
"splunk_add_on_ucc_framework/package/appserver/static/js/build/redirect_page.js",
"splunk_add_on_ucc_framework/package/appserver/static/styles/bootstrap.pcss",
"splunk_add_on_ucc_framework/package/appserver/templates/base.html",
"splunk_add_on_ucc_framework/package/appserver/templates/redirect.html",
"splunk_add_on_ucc_framework/package/default/data/ui/nav/default.xml",
"splunk_add_on_ucc_framework/package/default/data/ui/views/configuration.xml",
"splunk_add_on_ucc_framework/package/default/data/ui/views/inputs.xml",
"splunk_add_on_ucc_framework/package/default/data/ui/views/redirect.xml",
"splunk_add_on_ucc_framework/package/locale/messages.pot",
"splunk_add_on_ucc_framework/package/locale/zh_CN/LC_MESSAGES/messages.mo",
"splunk_add_on_ucc_framework/package/locale/zh_CN/LC_MESSAGES/messages.po",
"splunk_add_on_ucc_framework/requirements_py2.txt",
"splunk_add_on_ucc_framework/requirements_py3.txt",
"splunk_add_on_ucc_framework/requirements.txt",
    ]

readme = 'README.rst'  # Markdown files are supported

repository = "https://github.com/splunk/splunk-add-on-sdk-python/"
homepage = "https://github.com/splunk/splunk-add-on-sdk-python/"

keywords = ['splunk']

[tool.poetry.dependencies]
python = "^3.7"
solnlib = '^3.0'
splunk-sdk = "^1.6"
jinja2 = "^2"
mako= "^1"
munch= "^2"
lxml = "^4.3"
future = "^0"
splunktaucclib = "^4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.4"
pytest-splunk-addon = { version = "^1.3", extras = [ "docker" ] }
poetry-dynamic-versioning = "^0.8"

[tool.poetry-dynamic-versioning]
enable = true

[tool.poetry.scripts]
ucc-gen="splunk_add_on_ucc_framework:main"
build-ucc="build:build_ucc"
install-libs="splunk_add_on_ucc_framework:install_requirements"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"