[tool.poetry]
name = "debauto"
version = "0.2.3"
description = "Criação de remessas de débito automático no formato CNAB 150 da Febraban."
authors = ["Flavio Milan <oflaviomilan@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
