

jokes = ["Don't trust atoms, they make up everything.",
         "Moses had the first tablet that could connect to the cloud.",
         "There are 10 types of people in the world: those who understand binary, and those who don't",
         "CAPS LOCK - Preventing Login Since 1980.",
         "The Internet: where men are men, women are men, and children are FBI agents.",
         "Mac users swear by their Mac, PC users swear at their PC.",
         "Evolution is God's way of issuing upgrades.",
         "Employee of the month is a good example of how somebody can be both a winner and a loser at the same time.",
         "I don’t have a girlfriend, but I know a girl that would get really mad if she heard me say that.",
         "My drug test came back negative. My dealer sure has some explaining to do.",
         "The problem isn’t that obesity runs in your family. The problem is no one runs in your family.",
         "How to disable autocorrect in wife?",
         "If at first you don't succeed; call it version 1.0",
         "I'm not anti-social; I'm just not user friendly",
         "My software never has bugs. It just develops random features",
         "Roses are #FF0000 , Violets are #0000FF , All my base belongs to you",
         "In a world without fences and walls, who needs Gates and Windows?",
         "Hand over the calculator, friends don't let friends derive drunk",
         "I would love to change the world, but they won't give me the source code",
         "Enter any 11-digit prime number to continue...",
         "The box said 'Requires Windows 95 or better'. So I installed LINUX",
         "Alcohol is a perfect solvent: It dissolves marriages, families and careers.",
         "A penny saved is 1.39 cents earned, if you consider income tax",
         "Unix, DOS and Windows...the good, the bad and the ugly",
         "A computer lets you make more mistakes faster than any invention in human history - with the possible exceptions of handguns and tequila",
         "The code that is the hardest to debug is the code that you know cannot possibly be wrong",
         "UNIX is basically a simple operating system, but you have to be a genius to understand the simplicity",
         "C://dos C://dos.run run.dos.run",
         "You know it's love when you memorize her IP number to skip DNS overhead",
         "1f u c4n r34d th1s u r34lly n33d t0 g37 l41d",
         "Alcohol & calculus don't mix. Never drink & derive",
         "How do I set a laser printer to stun?",
         "Be nice to the nerds, for all you know they might be the next Bill Gates!",
         "Squash one bug, you'll see ten new bugs popping",
         "Everytime I touch my code, i give birth to ten new bugs",
         "Bad or corrupt header, go get a haircut",
         "Bad or missing mouse driver. Spank the cat? (Y/N)",
         "Hackers in hollywood movies are phenomenal. All they need to do is 'c:\\> hack into fbi'",
         "BREAKFAST.COM Halted...Cereal Port Not Responding",
         "File not found. Should I fake it? (Y/N)",
         "Cannot read data, leech the next boy's paper? (Y/N)",
         "The truth is out there...anybody got the URL?",
         "Smash forehead on keyboard to continue.....",
         "All wiyht. Rho sritched mg kegtops awound?",
         "Old programmers never die; they just give up their resources",
         "To err is human - and to blame it on a computer is even more so",
         "Computers can never replace human stupidity",
         "Unix is user friendly...its just selective about who its friends are",
         "Artificial intelligence usually beats real stupidity",
         "Black holes are where God divided by zero",
         "Yes! My code compiled, and my wife just produced the output",
         "I'm sorry, our software is perfect. The problem must be you",
         "Failure is not an option. It comes bundled with your Microsoft product",
         "How's my programming? Call 1-800-DEV-NULL",
         "Unix is the only virus with a command line interface",
         "How are we supposed to hack your system if it's always down!",
         "God is real, unless declared integer",
         "If Linux were a beer, it would be shipped in open barrels so that anybody could piss in it before delivery",
         "You sir, are an unknown USB device driver",
         "An SQL query goes into a bar, walks up to two tables and asks, 'Can I join you?'",
         "To understand recursion you must first understand recursion.",
         "What's the object-oriented way to become wealthy? Inheritance.",
         "How many programmers does it take to change a lightbulb? None, they just make darkness a standard.",
         "Two bytes meet. The first byte asks, 'Are you ill?' The second byte replies, 'No, just feeling a bit off.'",
         "Two threads walk into a bar. The barkeeper looks up and yells, 'Hey, I want don't any conditions race like time last!'",
         "Old C programmers don't die, they're just cast into void.",
         "Why did the programmer quit his job? Because he didn't get arrays.",
         "Why do Java programmers have to wear glasses? Because they don't see sharp.",
         "A programmer was found dead in the shower. Next to their body was a bottle of shampoo with the instructions 'Lather, Rinse and Repeat'.",
         "Optimist: The glass is half full. Pessimist: The glass is half empty. Programmer: The glass is twice as large as necessary.",
         "How many programmers does it take to kill a cockroach? Two: one holds, the other installs Windows on it.",
         "Child: Dad, why does the sun rise in the east and set in the west? Dad: Son, it's working, don't touch it.",
         "Why are you always smiling? That's just my... regular expression.",
         "Java: Write once, run away.",
         "I would tell you a joke about UDP, but you would never get it.",
         "A QA engineer walks into a bar. Runs into a bar. Crawls into a bar. Dances into a bar. Tiptoes into a bar. Rams a bar. Jumps into a bar.",
         "My friend's in a band called '1023 Megabytes'... They haven't got a gig yet!",
         "I had a problem so I thought I'd use Java. Now I have a ProblemFactory.",
         "QA Engineer walks into a bar. Orders a beer. Orders 0 beers. Orders 999999999 beers. Orders a lizard. Orders -1 beers. Orders a sfdeljknesv.",
         "How do you generate a random string? Put a first year Computer Science student in Vim and ask them to save and exit.",
         "I've been using Vim for a long time now, mainly because I can't figure out how to exit.",
         "How do you know whether a person is a Vim user? Don't worry, they'll tell you.",
         "Waiter: He's choking! Is anyone a doctor? Programmer: I'm a Vim user.",
         "3 Database Admins walked into a NoSQL bar. A little while later they walked out because they couldn't find a table.",
         "How to explain the movie Inception to a programmer? When you run a VM inside another VM, inside another VM ... everything runs real slow!",
         "There are only two hard problems in Computer Science: cache invalidation, naming things and off-by-one-errors.",
         "QAs consist of 55% water, 30% blood and 15% Jira tickets.",
         "Sympathy for the Devil is really just about being nice to QAs.",
         "How many QAs does it take to change a lightbulb? They noticed that the room was dark. They don't fix problems, they find them.",
         "A programmer crashes a car at the bottom of a hill, a bystander asks what happened, he says \"No idea. Let's push it back up and try again\".",
         "Writing PHP is like peeing in the swimming pool, everyone did it, but we don't need to bring it up in public.",
         "Schrodinger's attitude to web development: If I don't look at it in Internet Explorer then there's a chance it looks fine.",
         "I went to a street where the houses were numbered 8k, 16k, 32k, 64k, 128k, 256k and 512k. It was a trip down Memory Lane.",
         ]
