# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HelpGuide.ui',
# licensing of 'HelpGuide.ui' applies.
#
# Created: Fri Sep 18 16:31:48 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_HelpGuide(object):
    def setupUi(self, HelpGuide):
        HelpGuide.setObjectName("HelpGuide")
        HelpGuide.resize(1000, 800)
        font = QtGui.QFont()
        font.setPointSize(16)
        HelpGuide.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/ICONS/PFAS_SAT_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HelpGuide.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(HelpGuide)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(HelpGuide)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(HelpGuide)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(HelpGuide)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.link_Create_project = QtWidgets.QLabel(HelpGuide)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.link_Create_project.setFont(font)
        self.link_Create_project.setObjectName("link_Create_project")
        self.horizontalLayout.addWidget(self.link_Create_project)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(HelpGuide)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_6.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(True)
        self.label_6.setIndent(-1)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(HelpGuide)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_5.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.link_FA = QtWidgets.QLabel(HelpGuide)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.link_FA.setFont(font)
        self.link_FA.setObjectName("link_FA")
        self.horizontalLayout_6.addWidget(self.link_FA)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_6, 5, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(HelpGuide)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_15.setFont(font)
        self.label_15.setWordWrap(True)
        self.label_15.setIndent(-1)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 6, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 7, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(HelpGuide)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_4.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.link_MC = QtWidgets.QLabel(HelpGuide)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.link_MC.setFont(font)
        self.link_MC.setObjectName("link_MC")
        self.horizontalLayout_5.addWidget(self.link_MC)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_5, 8, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(HelpGuide)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_14.setFont(font)
        self.label_14.setWordWrap(True)
        self.label_14.setIndent(-1)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 9, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 10, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(HelpGuide)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_9.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.link_SA = QtWidgets.QLabel(HelpGuide)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.link_SA.setFont(font)
        self.link_SA.setObjectName("link_SA")
        self.horizontalLayout_7.addWidget(self.link_SA)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.gridLayout.addLayout(self.horizontalLayout_7, 11, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(HelpGuide)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_18.setFont(font)
        self.label_18.setWordWrap(True)
        self.label_18.setIndent(-1)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 12, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 13, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(HelpGuide)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_7.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.link_CodeDoc = QtWidgets.QLabel(HelpGuide)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.link_CodeDoc.setFont(font)
        self.link_CodeDoc.setObjectName("link_CodeDoc")
        self.horizontalLayout_3.addWidget(self.link_CodeDoc)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.gridLayout.addLayout(self.horizontalLayout_3, 14, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(HelpGuide)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_16.setFont(font)
        self.label_16.setWordWrap(True)
        self.label_16.setIndent(-1)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 15, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 16, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(HelpGuide)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_8.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.link_Contr = QtWidgets.QLabel(HelpGuide)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.link_Contr.setFont(font)
        self.link_Contr.setObjectName("link_Contr")
        self.horizontalLayout_2.addWidget(self.link_Contr)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.gridLayout.addLayout(self.horizontalLayout_2, 17, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(HelpGuide)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_17.setFont(font)
        self.label_17.setWordWrap(True)
        self.label_17.setIndent(-1)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 18, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem11, 19, 0, 1, 1)

        self.retranslateUi(HelpGuide)
        QtCore.QMetaObject.connectSlotsByName(HelpGuide)

    def retranslateUi(self, HelpGuide):
        HelpGuide.setWindowTitle(QtWidgets.QApplication.translate("HelpGuide", "PFAS SAT Help", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("HelpGuide", "Getting started guides", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("HelpGuide", "The following guides will help you get up and running quickly.", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("HelpGuide", "Create New Project", None, -1))
        self.link_Create_project.setText(QtWidgets.QApplication.translate("HelpGuide", "(Learn How)", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("HelpGuide", "You can create a new project by selecting the type and amount of incoming waste and then selecting the treatment processes.", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("HelpGuide", "Flow Analysis", None, -1))
        self.link_FA.setText(QtWidgets.QApplication.translate("HelpGuide", "(Learn How)", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("HelpGuide", "You can plot a Sankey diagram for PFAS flows through your treatment system.", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("HelpGuide", "Monte Carlo Simulation", None, -1))
        self.link_MC.setText(QtWidgets.QApplication.translate("HelpGuide", "(Learn How)", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("HelpGuide", "You can define the uncertainty distributions for the input data and then run the Monte Carlo simulation to study the effect of uncertainty/variability in the input data and find the most important input parameters.", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("HelpGuide", "Sensitivity Analysis", None, -1))
        self.link_SA.setText(QtWidgets.QApplication.translate("HelpGuide", "(Learn How)", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("HelpGuide", "You can perform parametric sensitivity analysis to study the effect of input parameters on the results.", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("HelpGuide", "Code Documentation", None, -1))
        self.link_CodeDoc.setText(QtWidgets.QApplication.translate("HelpGuide", "(Learn How)", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("HelpGuide", "You can also use the PFAS_SAT module via the command-line interface. The Command-line interface gives you the flexibility to do more customized/advanced analysis by exploiting the Python and other free scientific packages that the open-source community offers. Online code documentation is available to ease the understanding and use of code.", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("HelpGuide", "Contribution", None, -1))
        self.link_Contr.setText(QtWidgets.QApplication.translate("HelpGuide", "(Learn How)", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("HelpGuide", "Contributions are welcome, and they are greatly appreciated! You can report bugs, revise input data, or develop new process models for new technologies.", None, -1))

from . import PFAS_SAT_rc
