[tool.poetry]
name = "glortrou"
version = "0.0.0"
description = "An UDP hole-punching server, client and broker based on AsyncIO"
authors = ["Frank Chang <frank@csie.io>"]
license = "BSD-3-Clause"
readme = "README.md"
keywords = ["udp", "hole-punching", "p2p", "nat", "asyncio"]
repository = "https://github.com/frankurcrazy/glortrou"

[tool.poetry.dependencies]
python = "^3.6.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.5.3"
flake8 = "^3.8.3"
pre-commit = "^2.7.1"
semantic-release = "^0.1.0"
coverage = "^5.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
