version: 1

# database settings:
#     db: unit_tests
#     host: localhost
#     user: utuser
#     password: utpass
#     tunnel: False

database settings:
    static catalogues:
        db: unit_tests
        host: localhost
        user: utuser
        password: utpass
        tunnel: False

    static catalogues2:
        db: crossmatch_catalogues
        host: 127.0.0.1
        user: sherlock_readonly_user
        password: sherlock_readonly_pass
        tunnel: 
            remote user: dry
            remote ip: starbase2.mp.qub.ac.uk
            remote datbase host: db4
            port: 9017

    transients:
        user: utuser
        password: utpass
        db: unit_tests
        host: 127.0.0.1
        transient table: transientBucket
        transient count: "select count(*)
            from transientBucket t, pesstoObjects p
            where t.transientBucketId=p.transientBucketId
            and masterIdFlag = 1 and sherlockClassification is null "
        transient query: "select t.transientBucketId as 'id', t.transientBucketId as 'alt_id', raDeg 'ra', decDeg 'dec', name 'name', sherlockClassification as 'object_classification'
            from transientBucket t, pesstoObjects p
            where t.transientBucketId=p.transientBucketId
            and masterIdFlag = 1 and sherlockClassification is null"
        transient peak magnitude query: "select transientBucketId as 'id', min(magnitude) as 'mag' from transientBucket where magnitude is not null and limitingMag = 0 and magnitude > 2.0 group by id"
        transient primary id column: transientBucketId
        transient classification column: sherlockClassification
        crossmatchTable: sherlock_crossmatches
        tunnel: False


sherlock wiki root: ~/gh-wikis/sherlock.wiki/

# IFS Galaxies
ifs galaxies url: "https://raw.githubusercontent.com/lgalbany/lgalbany.github.io/master/GALBANY_PESSTO_ENV"
ned stream search radius arcec: 900
first pass ned search radius arcec: 240
ned stream refresh rate in days: 90
galaxy radius stetch factor: 1.2
synonym radius arcsec: 1.5

search algorithm:
    GSC star 1:
        database table: tcs_view_star_guide_star_catalogue_v2_3
        mag column: V
        bright:
            mag limit: 16.
            angular radius arcsec: 100.0
            synonym: VS
            association: BS
        faint:
            mag limit: 19.5
            angular radius arcsec: 3.0
            annotation: SN
        general:
            angular radius arcsec: 2.5
            synonym: VS
            association: VS
    GSC star 2:
        database table: tcs_view_star_guide_star_catalogue_v2_3
        mag column: B
        bright:
            mag limit: 16.
            angular radius arcsec: 100.0
            synonym: VS
            association: BS
        faint:
            mag limit: 19.5
            angular radius arcsec: 3.0
            annotation: SN
        general:
            angular radius arcsec: 2.5
            synonym: VS
            association: VS
    GSC unknown:
        database table: tcs_view_unknown_guide_star_catalogue_v2_3
        general:
            angular radius arcsec: 2.0
            annotation: UNCLEAR
    2mass star:
        database table: tcs_view_star_2mass_psc_final
        mag column: J
        faint:
            mag limit: 19.5
            angular radius arcsec: 3.0
            annotation: SN
        general:
            angular radius arcsec: 2.5
            synonym: VS
            association: VS
    2mass galaxy:
        database table: tcs_view_galaxy_2mass_xsc_final
        mag column: J
        bright:
            mag limit: 16.
            angular radius arcsec: 35.
            synonym: NT
            association: SN
        faint:
            mag limit: 20.5
            angular radius arcsec: 6.
            association: SN
        general:
            angular radius arcsec: 35.
            synonym: NT
            association: SN
    downes cv:
        database table: tcs_view_cv_downes_cataclysmic_variables_final
        general:
            angular radius arcsec: 2.5
            synonym: CV
            association: CV
    ritter binaries:
        database table: tcs_view_cb_ritter_cataclysmic_binaries_v7_21
        general:
            angular radius arcsec: 2.5
            synonym: CV
            association: CV
    gaia star:
        database table: tcs_view_star_gaia_dr2
        mag column: G
        bright:
            mag limit: 16.
            angular radius arcsec: 100.0
            synonym: VS
            association: BS
        general:
            angular radius arcsec: 5.0
            synonym: VS
            association: VS
    gaia galaxy:
        database table: tcs_view_unclear_gaia_dr2
        mag column: G
        general:
            angular radius arcsec: 3.0
            synonym: UNCLEAR
            association: SN
    ps1 star r:
        database table: tcs_view_star_ps1_dr1
        mag column: _r
        bright:
            mag limit: 16.
            angular radius arcsec: 100.0
            synonym: VS
            association: BS
        general:
            angular radius arcsec: 2.5
            synonym: VS
            association: VS
    ps1 star i:
        database table: tcs_view_star_ps1_dr1
        mag column: _i
        bright:
            mag limit: 16.
            angular radius arcsec: 100.0
            synonym: VS
            association: BS
        general:
            angular radius arcsec: 2.5
            synonym: VS
            association: VS
    ps1 galaxy r:
        database table: tcs_view_galaxy_ps1_dr1
        mag column: _r
        bright:
            mag limit: 16.
            angular radius arcsec: 100.0
            synonym: VS
            association: BS
        faint:
            mag limit: 20.
            angular radius arcsec: 6.
            association: SN
        general:
            angular radius arcsec: 35.
            association: SN
    ps1 galaxy i:
        database table: tcs_view_galaxy_ps1_dr1
        mag column: _i
        bright:
            mag limit: 16.
            angular radius arcsec: 100.0
            synonym: VS
            association: BS
        general:
            angular radius arcsec: 35.
            association: SN
        faint:
            mag limit: 20.
            angular radius arcsec: 6.
            association: SN
    ps1 faint sources r:
        database table: tcs_view_unclear_ps1_dr1
        mag column: _r
        general:
            angular radius arcsec: 1.0
            annotation: UNCLEAR
    ps1 faint sources i:
        database table: tcs_view_unclear_ps1_dr1
        mag column: _i
        general:
            angular radius arcsec: 1.0
            annotation: UNCLEAR
    kepler galaxy:
        database table: tcs_view_galaxy_kepler_k2
        mag column: _r
        bright:
            mag limit: 16.
            angular radius arcsec: 35.
            annotation: SN
        faint:
            mag limit: 20.5
            angular radius arcsec: 6.
            annotation: SN
        general:
            angular radius arcsec: 35.
            annotation: SN
    milliquas agn:
        database table: tcs_view_agn_milliquas_v5_2
        general:
            angular radius arcsec: 3.0
            synonym: AGN
            association: AGN
    veron agn:
        database table: tcs_view_agn_veron_v13
        general:
            angular radius arcsec: 3.0
            synonym: AGN
            association: AGN
    ned_d spec galaxy:
        database table: tcs_view_galaxy_ned_d_v13_1_0
        general:
            physical radius kpc: 50.0
            angular radius arcsec: 6000.0
            or within semi major axis: True
            synonym: NT
            association: SN
    ned spec galaxy:
        database table: tcs_view_galaxy_ned_stream
        general:
            physical radius kpc: 50.0
            angular radius arcsec: 240.0
            or within semi major axis: True
            synonym: NT
            association: SN
    ned phot galaxy:
        database table: tcs_view_galaxy_ned_stream
        mag column: unkMag
        bright:
            mag limit: 16.
            angular radius arcsec: 35.
            synonym: NT
            association: SN
        faint:
            mag limit: 20.
            angular radius arcsec: 6.
            association: SN
        general:
            angular radius arcsec: 35.
            synonym: NT
            association: SN
    ned phot galaxy-like:
        database table: tcs_view_galaxy_like_ned_stream
        general:
            angular radius arcsec: 10.
            annotation: SN
    sdss agn:
        database table: tcs_view_qso_sdss_spect_galaxies_qsos_dr12
        general:
            angular radius arcsec: 3.0
            synonym: AGN
            association: AGN
    ned agn:
        database table: tcs_view_agn_ned_stream
        general:
            angular radius arcsec: 3.0
            synonym: AGN
            association: AGN
    sdss star:
        database table: tcs_view_star_sdss_photo_stars_galaxies_dr12
        mag column: _r
        bright:
            mag limit: 16.
            angular radius arcsec: 100.0
            synonym: VS
            association: BS
        faint:
            mag limit: 21.0
            angular radius arcsec: 3.0
            annotation: SN
        general:
            angular radius arcsec: 2.5
            synonym: VS
            association: VS
    sdss phot galaxy:
        database table: tcs_view_galaxy_sdss_photo_stars_galaxies_dr12
        mag column: _r
        bright:
            bright:
            mag limit: 14.5
            angular radius arcsec: 100.0
            synonym: VS
            association: BS
        faint:
            mag limit: 20.
            angular radius arcsec: 6.
            association: SN
        general:
            angular radius arcsec: 35.
            synonym: NT
            association: SN
    sdss spec galaxy:
        database table: tcs_view_galaxy_sdss_spect_galaxies_qsos_dr12
        general:
            physical radius kpc: 50.0
            angular radius arcsec: 60.0
            or within semi major axis: True
            synonym: NT
            association: SN
    ned spec unknown:
        database table: tcs_view_other_ned_stream
        general:
            physical radius kpc: 50.0
            angular radius arcsec: 60.0
            synonym: UNCLEAR
            association: UNCLEAR
    ned phot unknown:
        database table: tcs_view_other_ned_stream
        general:
            angular radius arcsec: 20.
            annotation: UNCLEAR
    ned star:
        database table: tcs_view_star_ned_stream
        general:
            angular radius arcsec: 2.5
            synonym: VS
            association: VS
    glade agn:
        database table: tcs_view_agn_glade_v2_3
        general:
            angular radius arcsec: 2.5
            synonym: AGN
            association: AGN
    glade spec galaxy:
        database table: tcs_view_galaxy_glade_v2_3
        general:
            physical radius kpc: 50.0
            angular radius arcsec: 60.
            synonym: NT
            association: SN
    glade phot galaxy:
        database table: tcs_view_galaxy_glade_v2_3
        mag column: B
        bright:
            mag limit: 16.
            angular radius arcsec: 35.
            synonym: NT
            association: SN
        faint:
            mag limit: 20.
            angular radius arcsec: 6.
            association: SN
        general:
            angular radius arcsec: 35.
            synonym: NT
            association: SN
    glade phot galaxy 2:
        database table: tcs_view_galaxy_glade_v2_3
        mag column: J
        bright:
            mag limit: 16.
            angular radius arcsec: 35.
            synonym: NT
            association: SN
        faint:
            mag limit: 20.
            angular radius arcsec: 6.
            association: SN
        general:
            angular radius arcsec: 35.
            synonym: NT
            association: SN

# # SSH TUNNEL - if a tunnel is required to connect to the database(s) then add setup here
# # Note only one tunnel is setup - may need to change this to 2 tunnels in the future if 
# # code, static catalogue database and transient database are all on seperate machines.
# ssh tunnel:
#     remote user: username
#     remote ip: mydomain.co.uk
#     remote datbase host: mydatabaseName
#     port: 9002

logging settings:
    formatters:
        file_style:
            format: '* %(asctime)s - %(name)s - %(levelname)s (%(pathname)s > %(funcName)s > %(lineno)d) - %(message)s  '
            datefmt: '%Y/%m/%d %H:%M:%S'
        console_style:
            format: '* %(asctime)s - %(levelname)s: %(pathname)s:%(funcName)s:%(lineno)d > %(message)s'
            datefmt: '%H:%M:%S'
        html_style:
            format: '<div id="row" class="%(levelname)s"><span class="date">%(asctime)s</span>   <span class="label">file:</span><span class="filename">%(filename)s</span>   <span class="label">method:</span><span class="funcName">%(funcName)s</span>   <span class="label">line#:</span><span class="lineno">%(lineno)d</span> <span class="pathname">%(pathname)s</span>  <div class="right"><span class="message">%(message)s</span><span class="levelname">%(levelname)s</span></div></div>'
            datefmt: '%Y-%m-%d <span class= "time">%H:%M <span class= "seconds">%Ss</span></span>'
    handlers:
        console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: console_style
            stream: ext://sys.stdout
        file:
            class: logging.handlers.GroupWriteRotatingFileHandler
            level: WARNING
            formatter: file_style
            filename: ~/.config/sherlock/sherlock.log
            mode: w+
            maxBytes: 102400
            backupCount: 1
    root:
        level: WARNING
        handlers: [file,console]
