language: python
cache: pip
dist: bionic
matrix:
  include:
    - python: 2.7
      env: TOX_ENV="py27"
    - python: 3.6
      env: TOX_ENV="py36"
    - python: 3.7
      env: TOX_ENV="py37"
    - python: 3.8
      env: TOX_ENV="py38"
    - python: "3.9-dev"
      env: TOX_ENV="py39"
    - python: 3.8
      env: TOX_ENV="pylint"
    - python: 3.8
      env: TOX_ENV="style"
    - python: 3.8
      env: TOX_ENV="mypy"
    - python: 3.8
      env: TOX_ENV="docs"
install:
  - pip install tox
  - pip install --upgrade setuptools
script:
  - tox -e $TOX_ENV
