[tool.poetry]
name = "autogram-commons"
version = "0.1.0"
description = ""
authors = ["Joscha Götzer <joscha.goetzer@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = {extras = ["dotenv"], version = "^1.6.1"}
"ruamel.yaml" = "^0.16.12"

[tool.poetry.dev-dependencies]
pytest = "^6.0.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
