
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-19T23:57:37-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d3807dd8fca601edba7bd51888c2d701f290edaf",
 "version": "3.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
