
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-24T12:10:53-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e4b1abcc69a3f710779e87832ba4317a2912df5e",
 "version": "2020.9.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
