[tool.poetry]
name = "crystal_toolkit"
version = "2020.09.28"
description = ""
authors = ["Matthew Horton <mkhorton@lbl.gov>"]

[tool.poetry.dependencies]
python = "^3.7"
pymatgen = "^2020.9.14"
typing-extensions = { version = "^3.7", python = "~3.7" }
pydantic = "^1.4"
plotly = "^4.5.4"
webcolors = "^1.11.1"
ifermi = "^0.1.2"
pyfftw = "^0.12.0"

dash = { version = "^1.16", optional = true }
dash-daq = { version = "^0.4.0", optional = true }
gunicorn = { version = "^20.0.4", optional = true }
redis = { version = "^3.4.1", optional = true }
Flask-Caching = { version = "^1.8.0", optional = true }
gevent = { version = "^1.4.0", optional = true }
dash-mp-components = { version = ">=0.0.25", optional = true }
scikit-learn = { version = "^0.22.2", optional = true }
robocrys = { version = "^0.2.1", optional = true }
scikit-image = { version = "^0.17.2", optional = true }
habanero = { version = "^0.7.2", optional = true }
hiphive = { version = "^0.7", optional = true }
dscribe = { version = "^0.3.5", optional = true }
dash-extensions = { version = "^0.0.31", optional = true }
sentry-sdk = { version = "^0.17.3", optional = true }

[tool.poetry.extras]
server = [
    "dash", "dash-daq", "gunicorn", "redis",
    "Flask-Caching", "gevent", "dash-mp-components", "scikit-learn",
    "robocrys", "scikit-image", "habanero", "hiphive", "dscribe",
    "dash-extensions", "sentry-sdk"
]

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pre-commit = "^2.2.0"
dash = {extras = ["testing"], version = "^1.11.0"}
pytest = "^5.3.5"
sphinx = "^2.4.4"
sphinx_rtd_theme = "^0.4.3"
recommonmark = "^0.6.0"
dephell = "^0.8.2"

[tool.isort]
profile = "black"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

