language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install .[test]

script:
  - pytest -v sphinxcontrib

# Add separate test environments for the docs and flake8 linter.

jobs:
  include:
    - name: "Docs"
      script: python -m sphinx.cmd.build -E -W -v -T doc/source doc/build
    - name: "Lint"
      install: pip install flake8
      script: flake8 -v sphinxcontrib setup.py
    - name: "Check Package"
      install: pip install twine
      script:
        - python setup.py sdist
        - twine check dist/*.tar.gz

deploy:
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
  provider: pypi
  user: __token__
  password:
    secure: "GuFfI/o35Zw3b87aIKebLgcm8eBuhFRsBdHcPagdRdlibf+z34iq6QYcvl6GAdlttWZsSEvyBh35YJQPn6D0IyWjma/Plvxo3muI/uDFG1TcoMcbZWiUsmFO6W+PY2fEvPFAxuGTluj3SZ8bNfUr2z/8EaTbj9CFbrkxCapqPIz4CynMRP3M1b2U+3/7dzmTKn8/9EmpWbfZGvYSzLPnIX+SNx3RjhZXpWj51Ee8OSsq7RBIhM8IN3t1sYNtU+0uZLZiOolNyr74KQ/AIRoKVJ0T1LeQ96PdyIH6vSUopOdPs6g7jKdLLU8hFQH5zwxQBry/Qv+F8H55qI9nCRC1bejkc71onhVe9SNPpTurnpgVJXucl4alODEXfalxE0aNzuXfjq/NrnyQjLbrQH7cbCwc7Y6bo0c4Wvn/FKlB3nPjMZUx72mulheS6KVns/97Gbpi8MCBdBn8soDSSNpyGsVzgBVBkzmH8uCeee9UBkGr25rUoGUf1dcBBbWATkd0sr7IPvI636PNbtz1WW9RbOCHJ/UO0UElb419TvJhFd+/p0Gp9vtQ7LYsIdJdO/Pj8ho1+Hy9s017JN0W9bdtKXaEj7QXOAVRBh6sHLiLb8JpT20NxEcwgosGITBxNUjyudRxVseiJe9lImJuoLDEeIJOF5NLd8HMcAmA3AQvvHc="
