from google.ads.google_ads.v5.proto.services import ad_group_criterion_service_pb2 as ad_group_criterion_service_pb2
from google.ads.google_ads.v5.services import ad_group_criterion_service_client_config as ad_group_criterion_service_client_config
from google.ads.google_ads.v5.services.transports import ad_group_criterion_service_grpc_transport as ad_group_criterion_service_grpc_transport
from google.oauth2 import service_account as service_account
import grpc  # type: ignore
from google.ads.google_ads.v5.services.transports.ad_group_criterion_service_grpc_transport import AdGroupCriterionServiceGrpcTransport
from google.auth.credentials import Credentials  # type: ignore
from google.api_core.gapic_v1.client_info import ClientInfo  # type: ignore
from google.api_core.retry import Retry  # type: ignore
from typing import Optional, Dict, Any, List, Sequence, Tuple, Union, Callable, ClassVar
from google.ads.google_ads.v5.proto.resources.ad_group_criterion_pb2 import AdGroupCriterion

class AdGroupCriterionServiceClient:
    SERVICE_ADDRESS: ClassVar[str] = ...
    @classmethod
    def from_service_account_file(cls, filename: str, *args: Any, **kwargs: Any) -> AdGroupCriterionServiceClient: ...
    @classmethod
    def from_service_account_json(cls, filename: str, *args: Any, **kwargs: Any) -> AdGroupCriterionServiceClient: ...
    @classmethod
    def ad_group_criteria_path(cls, customer: Any, ad_group_criteria: Any) -> str: ...
    transport: Union[AdGroupCriterionServiceGrpcTransport, Callable[[Credentials, type], AdGroupCriterionServiceGrpcTransport]] = ...
    def __init__(self, transport: Optional[Any] = ..., channel: Optional[Any] = ..., credentials: Optional[Any] = ..., client_config: Optional[Any] = ..., client_info: Optional[Any] = ..., client_options: Optional[Any] = ...) -> None: ...
    def get_ad_group_criterion(self, resource_name: str, retry: Optional[Retry] = ..., timeout: Optional[float] = ..., metadata: Optional[Sequence[Tuple[str, str]]] = ...) -> AdGroupCriterion: ...
    def mutate_ad_group_criteria(self, customer_id: Any, operations: Any, partial_failure: Optional[Any] = ..., validate_only: Optional[Any] = ..., response_content_type: Optional[Any] = ..., retry: Any = ..., timeout: Any = ..., metadata: Optional[Any] = ...): ...
