from google.ads.google_ads.v5.proto.services import billing_setup_service_pb2 as billing_setup_service_pb2
from google.ads.google_ads.v5.services import billing_setup_service_client_config as billing_setup_service_client_config
from google.ads.google_ads.v5.services.transports import billing_setup_service_grpc_transport as billing_setup_service_grpc_transport
from google.oauth2 import service_account as service_account
import grpc  # type: ignore
from google.ads.google_ads.v5.services.transports.billing_setup_service_grpc_transport import BillingSetupServiceGrpcTransport
from google.auth.credentials import Credentials  # type: ignore
from google.api_core.gapic_v1.client_info import ClientInfo  # type: ignore
from google.api_core.retry import Retry  # type: ignore
from typing import Optional, Dict, Any, List, Sequence, Tuple, Union, Callable, ClassVar
from google.ads.google_ads.v5.proto.resources.billing_setup_pb2 import BillingSetup
from google.ads.google_ads.v5.proto.services.billing_setup_service_pb2 import BillingSetupOperation, MutateBillingSetupResponse

class BillingSetupServiceClient:
    SERVICE_ADDRESS: ClassVar[str] = ...
    @classmethod
    def from_service_account_file(cls, filename: str, *args: Any, **kwargs: Any) -> BillingSetupServiceClient: ...
    @classmethod
    def from_service_account_json(cls, filename: str, *args: Any, **kwargs: Any) -> BillingSetupServiceClient: ...
    @classmethod
    def billing_setup_path(cls, customer: Any, billing_setup: Any) -> str: ...
    transport: Union[BillingSetupServiceGrpcTransport, Callable[[Credentials, type], BillingSetupServiceGrpcTransport]] = ...
    def __init__(self, transport: Optional[Any] = ..., channel: Optional[Any] = ..., credentials: Optional[Any] = ..., client_config: Optional[Any] = ..., client_info: Optional[Any] = ..., client_options: Optional[Any] = ...) -> None: ...
    def get_billing_setup(self, resource_name: str, retry: Optional[Retry] = ..., timeout: Optional[float] = ..., metadata: Optional[Sequence[Tuple[str, str]]] = ...) -> BillingSetup: ...
    def mutate_billing_setup(self, customer_id: str, operation_: Union[Dict[str, Any], BillingSetupOperation], retry: Optional[Retry] = ..., timeout: Optional[float] = ..., metadata: Optional[Sequence[Tuple[str, str]]] = ...) -> MutateBillingSetupResponse: ...
