from google.ads.google_ads.v5.proto.services import campaign_asset_service_pb2 as campaign_asset_service_pb2
from google.ads.google_ads.v5.services import campaign_asset_service_client_config as campaign_asset_service_client_config
from google.ads.google_ads.v5.services.transports import campaign_asset_service_grpc_transport as campaign_asset_service_grpc_transport
from google.oauth2 import service_account as service_account
import grpc  # type: ignore
from google.ads.google_ads.v5.services.transports.campaign_asset_service_grpc_transport import CampaignAssetServiceGrpcTransport
from google.auth.credentials import Credentials  # type: ignore
from google.api_core.gapic_v1.client_info import ClientInfo  # type: ignore
from google.api_core.retry import Retry  # type: ignore
from typing import Optional, Dict, Any, List, Sequence, Tuple, Union, Callable, ClassVar
from google.ads.google_ads.v5.proto.resources.campaign_asset_pb2 import CampaignAsset
from google.ads.google_ads.v5.proto.services.campaign_asset_service_pb2 import CampaignAssetOperation, MutateCampaignAssetsResponse

class CampaignAssetServiceClient:
    SERVICE_ADDRESS: ClassVar[str] = ...
    @classmethod
    def from_service_account_file(cls, filename: str, *args: Any, **kwargs: Any) -> CampaignAssetServiceClient: ...
    @classmethod
    def from_service_account_json(cls, filename: str, *args: Any, **kwargs: Any) -> CampaignAssetServiceClient: ...
    @classmethod
    def campaign_asset_path(cls, customer: Any, campaign_asset: Any) -> str: ...
    transport: Union[CampaignAssetServiceGrpcTransport, Callable[[Credentials, type], CampaignAssetServiceGrpcTransport]] = ...
    def __init__(self, transport: Optional[Any] = ..., channel: Optional[Any] = ..., credentials: Optional[Any] = ..., client_config: Optional[Any] = ..., client_info: Optional[Any] = ..., client_options: Optional[Any] = ...) -> None: ...
    def get_campaign_asset(self, resource_name: str, retry: Optional[Retry] = ..., timeout: Optional[float] = ..., metadata: Optional[Sequence[Tuple[str, str]]] = ...) -> CampaignAsset: ...
    def mutate_campaign_assets(self, customer_id: str, operations: List[Union[Dict[str, Any], CampaignAssetOperation]], partial_failure: Optional[bool] = ..., validate_only: Optional[bool] = ..., retry: Optional[Retry] = ..., timeout: Optional[float] = ..., metadata: Optional[Sequence[Tuple[str, str]]] = ...) -> MutateCampaignAssetsResponse: ...
