from google.ads.google_ads.v5.proto.services import keyword_plan_ad_group_keyword_service_pb2 as keyword_plan_ad_group_keyword_service_pb2
from google.ads.google_ads.v5.services import keyword_plan_ad_group_keyword_service_client_config as keyword_plan_ad_group_keyword_service_client_config
from google.ads.google_ads.v5.services.transports import keyword_plan_ad_group_keyword_service_grpc_transport as keyword_plan_ad_group_keyword_service_grpc_transport
from google.oauth2 import service_account as service_account
import grpc  # type: ignore
from google.ads.google_ads.v5.services.transports.keyword_plan_ad_group_keyword_service_grpc_transport import KeywordPlanAdGroupKeywordServiceGrpcTransport
from google.auth.credentials import Credentials  # type: ignore
from google.api_core.gapic_v1.client_info import ClientInfo  # type: ignore
from google.api_core.retry import Retry  # type: ignore
from typing import Optional, Dict, Any, List, Sequence, Tuple, Union, Callable, ClassVar
from google.ads.google_ads.v5.proto.resources.keyword_plan_ad_group_keyword_pb2 import KeywordPlanAdGroupKeyword
from google.ads.google_ads.v5.proto.services.keyword_plan_ad_group_keyword_service_pb2 import KeywordPlanAdGroupKeywordOperation, MutateKeywordPlanAdGroupKeywordsResponse

class KeywordPlanAdGroupKeywordServiceClient:
    SERVICE_ADDRESS: ClassVar[str] = ...
    @classmethod
    def from_service_account_file(cls, filename: str, *args: Any, **kwargs: Any) -> KeywordPlanAdGroupKeywordServiceClient: ...
    @classmethod
    def from_service_account_json(cls, filename: str, *args: Any, **kwargs: Any) -> KeywordPlanAdGroupKeywordServiceClient: ...
    @classmethod
    def keyword_plan_ad_group_keyword_path(cls, customer: Any, keyword_plan_ad_group_keyword: Any) -> str: ...
    transport: Union[KeywordPlanAdGroupKeywordServiceGrpcTransport, Callable[[Credentials, type], KeywordPlanAdGroupKeywordServiceGrpcTransport]] = ...
    def __init__(self, transport: Optional[Any] = ..., channel: Optional[Any] = ..., credentials: Optional[Any] = ..., client_config: Optional[Any] = ..., client_info: Optional[Any] = ..., client_options: Optional[Any] = ...) -> None: ...
    def get_keyword_plan_ad_group_keyword(self, resource_name: str, retry: Optional[Retry] = ..., timeout: Optional[float] = ..., metadata: Optional[Sequence[Tuple[str, str]]] = ...) -> KeywordPlanAdGroupKeyword: ...
    def mutate_keyword_plan_ad_group_keywords(self, customer_id: str, operations: List[Union[Dict[str, Any], KeywordPlanAdGroupKeywordOperation]], partial_failure: Optional[bool] = ..., validate_only: Optional[bool] = ..., retry: Optional[Retry] = ..., timeout: Optional[float] = ..., metadata: Optional[Sequence[Tuple[str, str]]] = ...) -> MutateKeywordPlanAdGroupKeywordsResponse: ...
