from google.ads.google_ads.v5.proto.services import shared_criterion_service_pb2 as shared_criterion_service_pb2
from google.ads.google_ads.v5.services import shared_criterion_service_client_config as shared_criterion_service_client_config
from google.ads.google_ads.v5.services.transports import shared_criterion_service_grpc_transport as shared_criterion_service_grpc_transport
from google.oauth2 import service_account as service_account
import grpc  # type: ignore
from google.ads.google_ads.v5.services.transports.shared_criterion_service_grpc_transport import SharedCriterionServiceGrpcTransport
from google.auth.credentials import Credentials  # type: ignore
from google.api_core.gapic_v1.client_info import ClientInfo  # type: ignore
from google.api_core.retry import Retry  # type: ignore
from typing import Optional, Dict, Any, List, Sequence, Tuple, Union, Callable, ClassVar
from google.ads.google_ads.v5.proto.resources.shared_criterion_pb2 import SharedCriterion
from google.ads.google_ads.v5.proto.services.shared_criterion_service_pb2 import SharedCriterionOperation, MutateSharedCriteriaResponse

class SharedCriterionServiceClient:
    SERVICE_ADDRESS: ClassVar[str] = ...
    @classmethod
    def from_service_account_file(cls, filename: str, *args: Any, **kwargs: Any) -> SharedCriterionServiceClient: ...
    @classmethod
    def from_service_account_json(cls, filename: str, *args: Any, **kwargs: Any) -> SharedCriterionServiceClient: ...
    @classmethod
    def shared_criteria_path(cls, customer: Any, shared_criteria: Any) -> str: ...
    transport: Union[SharedCriterionServiceGrpcTransport, Callable[[Credentials, type], SharedCriterionServiceGrpcTransport]] = ...
    def __init__(self, transport: Optional[Any] = ..., channel: Optional[Any] = ..., credentials: Optional[Any] = ..., client_config: Optional[Any] = ..., client_info: Optional[Any] = ..., client_options: Optional[Any] = ...) -> None: ...
    def get_shared_criterion(self, resource_name: str, retry: Optional[Retry] = ..., timeout: Optional[float] = ..., metadata: Optional[Sequence[Tuple[str, str]]] = ...) -> SharedCriterion: ...
    def mutate_shared_criteria(self, customer_id: str, operations: List[Union[Dict[str, Any], SharedCriterionOperation]], partial_failure: Optional[bool] = ..., validate_only: Optional[bool] = ..., retry: Optional[Retry] = ..., timeout: Optional[float] = ..., metadata: Optional[Sequence[Tuple[str, str]]] = ...) -> MutateSharedCriteriaResponse: ...
