
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-29T15:37:12-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "07339a14aac083f7df151a897dae6dbe39d1b52a",
 "version": "1.7.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
