#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pyrpm']

package_data = \
{'': ['*']}

setup(name='python-rpm-spec',
      version='0.10',
      description='python-rpm-spec is a Python library for parsing RPM spec files.',
      author='Benjamin Kircher',
      author_email='bkircher@0xadd.de',
      url='https://github.com/bkircher/python-rpm-spec',
      packages=packages,
      package_data=package_data,
      python_requires='>=3.3',
     )
