from google.ads.google_ads.v5.proto.services import account_link_service_pb2 as account_link_service_pb2
from google.ads.google_ads.v5.services import account_link_service_client_config as account_link_service_client_config
from google.ads.google_ads.v5.services.transports import account_link_service_grpc_transport as account_link_service_grpc_transport
from google.oauth2 import service_account as service_account
import grpc  # type: ignore
from google.ads.google_ads.v5.services.transports.account_link_service_grpc_transport import AccountLinkServiceGrpcTransport
from google.auth.credentials import Credentials  # type: ignore
from google.api_core.gapic_v1.client_info import ClientInfo  # type: ignore
from google.api_core.retry import Retry  # type: ignore
from typing import Optional, Dict, Any, List, Sequence, Tuple, Union, Callable, ClassVar
from google.ads.google_ads.v5.proto.resources.account_link_pb2 import AccountLink

class AccountLinkServiceClient:
    SERVICE_ADDRESS: ClassVar[str] = ...
    @classmethod
    def from_service_account_file(cls, filename: str, *args: Any, **kwargs: Any) -> AccountLinkServiceClient: ...
    @classmethod
    def from_service_account_json(cls, filename: str, *args: Any, **kwargs: Any) -> AccountLinkServiceClient: ...
    @classmethod
    def account_link_path(cls, customer: Any, account_link: Any) -> str: ...
    transport: Union[AccountLinkServiceGrpcTransport, Callable[[Credentials, type], AccountLinkServiceGrpcTransport]] = ...
    def __init__(self, transport: Optional[Any] = ..., channel: Optional[Any] = ..., credentials: Optional[Any] = ..., client_config: Optional[Any] = ..., client_info: Optional[Any] = ..., client_options: Optional[Any] = ...) -> None: ...
    def get_account_link(self, resource_name: str, retry: Optional[Retry] = ..., timeout: Optional[float] = ..., metadata: Optional[Sequence[Tuple[str, str]]] = ...) -> AccountLink: ...
    def create_account_link(self, customer_id: Any, account_link: Any, retry: Any = ..., timeout: Any = ..., metadata: Optional[Any] = ...): ...
    def mutate_account_link(self, customer_id: Any, operation_: Any, partial_failure: Optional[Any] = ..., validate_only: Optional[Any] = ..., retry: Any = ..., timeout: Any = ..., metadata: Optional[Any] = ...): ...
