from google.ads.google_ads.v5.proto.services import asset_service_pb2 as asset_service_pb2
from google.ads.google_ads.v5.services import asset_service_client_config as asset_service_client_config
from google.ads.google_ads.v5.services.transports import asset_service_grpc_transport as asset_service_grpc_transport
from google.oauth2 import service_account as service_account
import grpc  # type: ignore
from google.ads.google_ads.v5.services.transports.asset_service_grpc_transport import AssetServiceGrpcTransport
from google.auth.credentials import Credentials  # type: ignore
from google.api_core.gapic_v1.client_info import ClientInfo  # type: ignore
from google.api_core.retry import Retry  # type: ignore
from typing import Optional, Dict, Any, List, Sequence, Tuple, Union, Callable, ClassVar
from google.ads.google_ads.v5.proto.resources.asset_pb2 import Asset

class AssetServiceClient:
    SERVICE_ADDRESS: ClassVar[str] = ...
    @classmethod
    def from_service_account_file(cls, filename: str, *args: Any, **kwargs: Any) -> AssetServiceClient: ...
    @classmethod
    def from_service_account_json(cls, filename: str, *args: Any, **kwargs: Any) -> AssetServiceClient: ...
    @classmethod
    def asset_path(cls, customer: Any, asset: Any) -> str: ...
    transport: Union[AssetServiceGrpcTransport, Callable[[Credentials, type], AssetServiceGrpcTransport]] = ...
    def __init__(self, transport: Optional[Any] = ..., channel: Optional[Any] = ..., credentials: Optional[Any] = ..., client_config: Optional[Any] = ..., client_info: Optional[Any] = ..., client_options: Optional[Any] = ...) -> None: ...
    def get_asset(self, resource_name: str, retry: Optional[Retry] = ..., timeout: Optional[float] = ..., metadata: Optional[Sequence[Tuple[str, str]]] = ...) -> Asset: ...
    def mutate_assets(self, customer_id: Any, operations: Any, response_content_type: Optional[Any] = ..., retry: Any = ..., timeout: Any = ..., metadata: Optional[Any] = ...): ...
