from google.ads.google_ads.v5.proto.services import label_service_pb2 as label_service_pb2
from google.ads.google_ads.v5.services import label_service_client_config as label_service_client_config
from google.ads.google_ads.v5.services.transports import label_service_grpc_transport as label_service_grpc_transport
from google.oauth2 import service_account as service_account
import grpc  # type: ignore
from google.ads.google_ads.v5.services.transports.label_service_grpc_transport import LabelServiceGrpcTransport
from google.auth.credentials import Credentials  # type: ignore
from google.api_core.gapic_v1.client_info import ClientInfo  # type: ignore
from google.api_core.retry import Retry  # type: ignore
from typing import Optional, Dict, Any, List, Sequence, Tuple, Union, Callable, ClassVar
from google.ads.google_ads.v5.proto.resources.label_pb2 import Label

class LabelServiceClient:
    SERVICE_ADDRESS: ClassVar[str] = ...
    @classmethod
    def from_service_account_file(cls, filename: str, *args: Any, **kwargs: Any) -> LabelServiceClient: ...
    @classmethod
    def from_service_account_json(cls, filename: str, *args: Any, **kwargs: Any) -> LabelServiceClient: ...
    @classmethod
    def label_path(cls, customer: Any, label: Any) -> str: ...
    transport: Union[LabelServiceGrpcTransport, Callable[[Credentials, type], LabelServiceGrpcTransport]] = ...
    def __init__(self, transport: Optional[Any] = ..., channel: Optional[Any] = ..., credentials: Optional[Any] = ..., client_config: Optional[Any] = ..., client_info: Optional[Any] = ..., client_options: Optional[Any] = ...) -> None: ...
    def get_label(self, resource_name: str, retry: Optional[Retry] = ..., timeout: Optional[float] = ..., metadata: Optional[Sequence[Tuple[str, str]]] = ...) -> Label: ...
    def mutate_labels(self, customer_id: Any, operations: Any, partial_failure: Optional[Any] = ..., validate_only: Optional[Any] = ..., response_content_type: Optional[Any] = ..., retry: Any = ..., timeout: Any = ..., metadata: Optional[Any] = ...): ...
