from google.ads.google_ads.v5.proto.services import media_file_service_pb2 as media_file_service_pb2
from google.ads.google_ads.v5.services import media_file_service_client_config as media_file_service_client_config
from google.ads.google_ads.v5.services.transports import media_file_service_grpc_transport as media_file_service_grpc_transport
from google.oauth2 import service_account as service_account
import grpc  # type: ignore
from google.ads.google_ads.v5.services.transports.media_file_service_grpc_transport import MediaFileServiceGrpcTransport
from google.auth.credentials import Credentials  # type: ignore
from google.api_core.gapic_v1.client_info import ClientInfo  # type: ignore
from google.api_core.retry import Retry  # type: ignore
from typing import Optional, Dict, Any, List, Sequence, Tuple, Union, Callable, ClassVar
from google.ads.google_ads.v5.proto.resources.media_file_pb2 import MediaFile

class MediaFileServiceClient:
    SERVICE_ADDRESS: ClassVar[str] = ...
    @classmethod
    def from_service_account_file(cls, filename: str, *args: Any, **kwargs: Any) -> MediaFileServiceClient: ...
    @classmethod
    def from_service_account_json(cls, filename: str, *args: Any, **kwargs: Any) -> MediaFileServiceClient: ...
    @classmethod
    def media_file_path(cls, customer: Any, media_file: Any) -> str: ...
    transport: Union[MediaFileServiceGrpcTransport, Callable[[Credentials, type], MediaFileServiceGrpcTransport]] = ...
    def __init__(self, transport: Optional[Any] = ..., channel: Optional[Any] = ..., credentials: Optional[Any] = ..., client_config: Optional[Any] = ..., client_info: Optional[Any] = ..., client_options: Optional[Any] = ...) -> None: ...
    def get_media_file(self, resource_name: str, retry: Optional[Retry] = ..., timeout: Optional[float] = ..., metadata: Optional[Sequence[Tuple[str, str]]] = ...) -> MediaFile: ...
    def mutate_media_files(self, customer_id: Any, operations: Any, partial_failure: Optional[Any] = ..., validate_only: Optional[Any] = ..., response_content_type: Optional[Any] = ..., retry: Any = ..., timeout: Any = ..., metadata: Optional[Any] = ...): ...
