from google.ads.google_ads.v5.proto.services import mobile_app_category_constant_service_pb2 as mobile_app_category_constant_service_pb2
from google.ads.google_ads.v5.services import mobile_app_category_constant_service_client_config as mobile_app_category_constant_service_client_config
from google.ads.google_ads.v5.services.transports import mobile_app_category_constant_service_grpc_transport as mobile_app_category_constant_service_grpc_transport
from google.oauth2 import service_account as service_account
import grpc  # type: ignore
from google.ads.google_ads.v5.services.transports.mobile_app_category_constant_service_grpc_transport import MobileAppCategoryConstantServiceGrpcTransport
from google.auth.credentials import Credentials  # type: ignore
from google.api_core.gapic_v1.client_info import ClientInfo  # type: ignore
from google.api_core.retry import Retry  # type: ignore
from typing import Optional, Dict, Any, List, Sequence, Tuple, Union, Callable, ClassVar
from google.ads.google_ads.v5.proto.resources.mobile_app_category_constant_pb2 import MobileAppCategoryConstant

class MobileAppCategoryConstantServiceClient:
    SERVICE_ADDRESS: ClassVar[str] = ...
    @classmethod
    def from_service_account_file(cls, filename: str, *args: Any, **kwargs: Any) -> MobileAppCategoryConstantServiceClient: ...
    @classmethod
    def from_service_account_json(cls, filename: str, *args: Any, **kwargs: Any) -> MobileAppCategoryConstantServiceClient: ...
    @classmethod
    def mobile_app_category_constant_path(cls, mobile_app_category_constant: Any): ...
    transport: Union[MobileAppCategoryConstantServiceGrpcTransport, Callable[[Credentials, type], MobileAppCategoryConstantServiceGrpcTransport]] = ...
    def __init__(self, transport: Optional[Any] = ..., channel: Optional[Any] = ..., credentials: Optional[Any] = ..., client_config: Optional[Any] = ..., client_info: Optional[Any] = ..., client_options: Optional[Any] = ...) -> None: ...
    def get_mobile_app_category_constant(self, resource_name: str, retry: Optional[Retry] = ..., timeout: Optional[float] = ..., metadata: Optional[Sequence[Tuple[str, str]]] = ...) -> MobileAppCategoryConstant: ...
