from google.ads.google_ads.v5.proto.services import remarketing_action_service_pb2 as remarketing_action_service_pb2
from google.ads.google_ads.v5.services import remarketing_action_service_client_config as remarketing_action_service_client_config
from google.ads.google_ads.v5.services.transports import remarketing_action_service_grpc_transport as remarketing_action_service_grpc_transport
from google.oauth2 import service_account as service_account
import grpc  # type: ignore
from google.ads.google_ads.v5.services.transports.remarketing_action_service_grpc_transport import RemarketingActionServiceGrpcTransport
from google.auth.credentials import Credentials  # type: ignore
from google.api_core.gapic_v1.client_info import ClientInfo  # type: ignore
from google.api_core.retry import Retry  # type: ignore
from typing import Optional, Dict, Any, List, Sequence, Tuple, Union, Callable, ClassVar
from google.ads.google_ads.v5.proto.resources.remarketing_action_pb2 import RemarketingAction
from google.ads.google_ads.v5.proto.services.remarketing_action_service_pb2 import RemarketingActionOperation, MutateRemarketingActionsResponse

class RemarketingActionServiceClient:
    SERVICE_ADDRESS: ClassVar[str] = ...
    @classmethod
    def from_service_account_file(cls, filename: str, *args: Any, **kwargs: Any) -> RemarketingActionServiceClient: ...
    @classmethod
    def from_service_account_json(cls, filename: str, *args: Any, **kwargs: Any) -> RemarketingActionServiceClient: ...
    @classmethod
    def remarketing_action_path(cls, customer: Any, remarketing_action: Any) -> str: ...
    transport: Union[RemarketingActionServiceGrpcTransport, Callable[[Credentials, type], RemarketingActionServiceGrpcTransport]] = ...
    def __init__(self, transport: Optional[Any] = ..., channel: Optional[Any] = ..., credentials: Optional[Any] = ..., client_config: Optional[Any] = ..., client_info: Optional[Any] = ..., client_options: Optional[Any] = ...) -> None: ...
    def get_remarketing_action(self, resource_name: str, retry: Optional[Retry] = ..., timeout: Optional[float] = ..., metadata: Optional[Sequence[Tuple[str, str]]] = ...) -> RemarketingAction: ...
    def mutate_remarketing_actions(self, customer_id: str, operations: List[Union[Dict[str, Any], RemarketingActionOperation]], partial_failure: Optional[bool] = ..., validate_only: Optional[bool] = ..., retry: Optional[Retry] = ..., timeout: Optional[float] = ..., metadata: Optional[Sequence[Tuple[str, str]]] = ...) -> MutateRemarketingActionsResponse: ...
