from google.ads.google_ads.v5.proto.services import shared_set_service_pb2 as shared_set_service_pb2
from google.ads.google_ads.v5.services import shared_set_service_client_config as shared_set_service_client_config
from google.ads.google_ads.v5.services.transports import shared_set_service_grpc_transport as shared_set_service_grpc_transport
from google.oauth2 import service_account as service_account
import grpc  # type: ignore
from google.ads.google_ads.v5.services.transports.shared_set_service_grpc_transport import SharedSetServiceGrpcTransport
from google.auth.credentials import Credentials  # type: ignore
from google.api_core.gapic_v1.client_info import ClientInfo  # type: ignore
from google.api_core.retry import Retry  # type: ignore
from typing import Optional, Dict, Any, List, Sequence, Tuple, Union, Callable, ClassVar
from google.ads.google_ads.v5.proto.resources.shared_set_pb2 import SharedSet

class SharedSetServiceClient:
    SERVICE_ADDRESS: ClassVar[str] = ...
    @classmethod
    def from_service_account_file(cls, filename: str, *args: Any, **kwargs: Any) -> SharedSetServiceClient: ...
    @classmethod
    def from_service_account_json(cls, filename: str, *args: Any, **kwargs: Any) -> SharedSetServiceClient: ...
    @classmethod
    def shared_set_path(cls, customer: Any, shared_set: Any) -> str: ...
    transport: Union[SharedSetServiceGrpcTransport, Callable[[Credentials, type], SharedSetServiceGrpcTransport]] = ...
    def __init__(self, transport: Optional[Any] = ..., channel: Optional[Any] = ..., credentials: Optional[Any] = ..., client_config: Optional[Any] = ..., client_info: Optional[Any] = ..., client_options: Optional[Any] = ...) -> None: ...
    def get_shared_set(self, resource_name: str, retry: Optional[Retry] = ..., timeout: Optional[float] = ..., metadata: Optional[Sequence[Tuple[str, str]]] = ...) -> SharedSet: ...
    def mutate_shared_sets(self, customer_id: Any, operations: Any, partial_failure: Optional[Any] = ..., validate_only: Optional[Any] = ..., response_content_type: Optional[Any] = ..., retry: Any = ..., timeout: Any = ..., metadata: Optional[Any] = ...): ...
