[tool.poetry]
name = "bssapi-schemas"
version = "0.1.0"
description = "Схемы BSS"
authors = ["Anton Rastyazhenko <rastyazhenko.anton@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.6.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
