[tool.poetry]
name = "vbml"
version = "1.1"
description = "Way to check, match & resist. Sofisticated object oriented regex-based text parser"
authors = ["timoniq"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/tesseradecade/vbml"
repository = "https://github.com/tesseradecade/vbml"
keywords = ["parser", "string", "string-manipulation", "string-matching"]
classifiers = [
  "Environment :: Console",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Software Development :: Quality Assurance",
  "Typing :: Typed",
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/tesseradecade/vbml/issues"

[tool.poetry.dependencies]
python = "^3.7"
typing_extensions = "^3.7.4"

[tool.poetry.dev-dependencies]
# Lint
lxml = "^4.5.0"
mypy = "^0.770"
isort = "^4.3"
flake8 = "^3.7.9"
mypy_extensions = "^0.4.3"
black = {version = "^19.0", allow-prereleases = true}

# Docs
mkdocs = "^1.1"
mkdocs-material = "^4.6"
mkautodoc = "^0.1.0"
pymdown-extensions = "^6.1"

# Tests
pytest = "^5.4"
pytest-cov = "^2.8"

[tool.black]
line-length = 99
target-version = ['py37', 'py38']
exclude = '''
(
    \.eggs
  | \.git
  | \.tox
  | build
  | dist
  | venv
  | docs
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 99

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
