
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-24T14:59:07-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "665eb8d7413877690d5cd1bed3505ddc3e874d0a",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
