version: 2
updates:
  # glean-core
  - package-ecosystem: "cargo"
    directory: "/glean-core"
    schedule:
      interval: "daily"
    ignore:
      # Pinned to old version due to breaking changes
      - dependency-name: "rkv"

  # glean-ffi
  - package-ecosystem: "cargo"
    directory: "/glean-core/ffi"
    schedule:
      interval: "daily"

  # glean benchmark
  - package-ecosystem: "cargo"
    directory: "/glean-core/benchmark"
    schedule:
      interval: "daily"

  # glean-python
  - package-ecosystem: "pip"
    directory: "/glean-core/python"
    schedule:
      interval: "daily"
    ignore:
      # Updated in lockstep across all implementations
      - dependency-name: "glean_parser"
