from .test_adapter import TestAdapter
from .test_allow_merge_items import TestAllowMergeItems
from .test_exceptions import TestExceptions
from .test_item_hooks import TestItemHooks
from .test_resolve_model import TestResolveModel
from .test_model_deleter import TestModelDeleter
from .test_norewrite import TestNorewrite
from .test_persist import TestPersist
from .test_replace import TestReplace
from .test_simple_config import TestSimpleConfig
