# coding: utf-8

"""
    Model Management Service

    Model Management System (MMS) is a version control system for structured data. It exposes model information through RESTful web services that can be used for CRUD operations, branching, and tagging of the model repository.  # noqa: E501

    OpenAPI spec version: 3.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mms_python_client
from mms_python_client.api.ref_api import RefApi  # noqa: E501
from mms_python_client.rest import ApiException


class TestRefApi(unittest.TestCase):
    """RefApi unit test stubs"""

    def setUp(self):
        self.api = mms_python_client.api.ref_api.RefApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_ref(self):
        """Test case for delete_ref

        Delete ref  # noqa: E501
        """
        pass

    def test_get_ref(self):
        """Test case for get_ref

        Get ref  # noqa: E501
        """
        pass

    def test_get_ref_history(self):
        """Test case for get_ref_history

        Get ref history  # noqa: E501
        """
        pass

    def test_get_refs(self):
        """Test case for get_refs

        Get all refs in project  # noqa: E501
        """
        pass

    def test_post_refs(self):
        """Test case for post_refs

        Create and/or update ref(s)  # noqa: E501
        """
        pass

    def test_projects_project_id_refs_ref_id_documents_get(self):
        """Test case for projects_project_id_refs_ref_id_documents_get

        Get ref history  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
