[tool.poetry]
name = "django-admin-display"
version = "1.2.0"
description = "Simplifies the use of function attributes for the django admin and makes mypy happy"
authors = [
    "Alexander Frenzel <alex@relatedworks.com>",
]

license = "BSD-3-Clause"
readme = "README.md"

documentation = "https://github.com/escaped/django-admin-display/blob/master/README.md"
homepage = "https://github.com/escaped/django-admin-display"
repository = "https://github.com/escaped/django-admin-display"

classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Web Environment",
  "Framework :: Django",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.6",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Typing :: Typed",
]

include = ["django_admin_display/py.typed"]

[tool.poetry.dependencies]
python = ">=3.6.1, <4.0"
# django = ">=1.11"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
isort = "^5.5.2"
mypy = "^0.782"
pre-commit = "^2.7.1"
pytest = "^6.0.1"
pytest-cov = "^2.10.1"
pytest-django = "^3.9.0"
pytest-mock = "^3.3.1"
tox = "^3.20.0"
tox-gh-actions = "^1.3.0"
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0b1"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 90
target-version = ['py36', 'py37', 'py38']
# this repository follows the convention
#   single quote: internal string
#   double quotes: user facing string
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
