[tool.poetry]
name = "basecamper"
version = "v0.10.49"
description = "Training utility library and config manager for Granular Machine Vision research"
authors = ["Sagar Verma <sagar@granular.ai>", "Siddharth Gupta <sid@granular.ai>"]
license = "MIT"
readme = "README.rst"
classifiers = [
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Natural Language :: English',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
]
repository='https://github.com/granularai/basecamper'

[tool.poetry.dependencies]
python = "^3.6.1"
arrow = "^0.16.0"
cookiecutter = "^1.7.2"


[tool.poetry.dev-dependencies]


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
