-   id: web-compile
    name: Compile Web Assets
    description: This hook compiles SCSS to CSS and minifies JS.
    entry: web-compile
    language: python
    language_version: python3
    require_serial: true
    pass_filenames: false
    # types: [css, javascript, jinja2, json, scss, toml, yaml]
    types: [text]
