[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "django_boilerplate_rest"
author = "Ravuthz"
author-email = "ravuthz@gmail.com"
home-page = "https://github.com/ravuthz/django_boilerplate/tree/rest"

requires=[
    "django-environ==0.4.5",
    "django-constance==2.7.0",
    "dj-database-url==0.5.0",
    "django-extensions==3.0.9",
    "djangorestframework==3.11.1",
    "django-rest-auth==0.9.5",
    "django-oauth-toolkit==1.3.2",
    "django-cors-headers==3.5.0",
    "drf-yasg==1.17.1",
]
requires-python=">=3.5"
description-file="README.md"

#classifiers = ["License :: OSI Approved :: MIT License"]
classifiers=[
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 3.1",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]
