
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-23T00:48:09-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "22db00afa338d3c76ee5ea45a26826a17ba53e89",
 "version": "1.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
