
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-24T17:27:32-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ed6fdb0ee853cb02919be8cf9438c073bd945b49",
 "version": "2020.9.24.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
