# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from event_pb2 import (
    Entity as event_pb2___Entity,
    Event as event_pb2___Event,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class HydrateRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def event(self) -> event_pb2___Event: ...

    def __init__(self,
        *,
        event : typing___Optional[event_pb2___Event] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"event",b"event"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"event",b"event"]) -> None: ...
type___HydrateRequest = HydrateRequest

class HydrateResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def event(self) -> event_pb2___Event: ...

    def __init__(self,
        *,
        event : typing___Optional[event_pb2___Event] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"event",b"event"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"event",b"event"]) -> None: ...
type___HydrateResponse = HydrateResponse

class HydrateAndIndexRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    organization_id: typing___Text = ...

    @property
    def entities(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[event_pb2___Entity]: ...

    def __init__(self,
        *,
        organization_id : typing___Optional[typing___Text] = None,
        entities : typing___Optional[typing___Iterable[event_pb2___Entity]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"entities",b"entities",u"organization_id",b"organization_id"]) -> None: ...
type___HydrateAndIndexRequest = HydrateAndIndexRequest
