[tool.poetry]
name = "git-cu"
version = "0.5.0"
description = "git-cu helps keep your local git repositories organized by cloning them into a directory structure based on their URL."
authors = ["Vasili Revelas <vasili.revelas@gmail.com>"]
license = "GPL-3.0-only"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pylint = "^2.5.2"
yapf = "^0.30.0"
pytest = "^6.0.2"
pytest-mock = "^3.3.1"
tbump = "^6.1.1"
mypy = "^0.782"

[tool.poetry.scripts]
git-cu = 'git_cu.main:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
