# Generated by Django 3.0.6 on 2020-09-20 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('genviews', '0002_genericglobalhistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenericGlobalHistory',
            new_name='GlobalHistory',
        ),
    ]
