[tool.poetry]
name = "bart-extract-ga"
packages = [ 
    { include="extract", from="." }
]
version = "0.1.0"
description = ""
authors = ["Cesar Augusto <cesarabruschetta@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.6.1,<3.7"
s3fs = "^0.4.2"
pyarrow = "^0.17.1"
google-api-python-client = "1.9.1"
pandas = "^1.0.4"

[tool.poetry.dev-dependencies]
pyspark = "^2.4.6"
black = "^19.10b0"
findspark = "^1.4.2"
boto3 = "^1.14.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
