language: rust
dist: "trusty"
before_install:
  - pyenv install 3.6.3
  - pyenv global 3.6.3

install:
  - pip3 install virtualenv
  - make update-venv
  - make setup
  - source venv/bin/activate

before_script:
  - make check

jobs:
  include:
    - name: pytest
      script: pytest svdtools
    - name: check_esp32
      script: bash tools/check_esp32.sh
    - name: check_esp8266
      script: bash tools/check_esp8266.sh
    - name: check_stm32
      script: bash tools/check_stm32.sh
    - name: check_lpc55
      script: bash tools/check_lpc55.sh
  allow_failures:
    - name: check_esp32
      script: bash tools/check_esp32.sh
  fast_finish: true

branches:
  only:
    - staging
    - trying
    - master
