
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-22T15:31:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f15b984bf10898c933875471355924207c4a4419",
 "version": "v1.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
