[tool.poetry]
name = "fittrackee"
version = "0.4.0"
description = "Self-hosted outdoor workout/activity tracker"
authors = ["SamR1"]
license = "GPL-3.0"
readme = "README.md"
homepage = "https://github.com/SamR1/FitTrackee"
documentation = "https://samr1.github.io/FitTrackee"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Framework :: Flask",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: JavaScript"
]
exclude = ["fittrackee/tests"]

[tool.poetry.dependencies]
python = "^3.7"
flask = "^1.1"
flask-migrate = "^2.5"
flask-bcrypt = "^0.7.1"
pyjwt = "^1.7"
gpxpy = "=1.3.4"
psycopg2-binary = "^2.8"
staticmap = "^0.5.4"
pytz = "^2020.1"
python-forecastio = "^1.4"
gunicorn = "^20.0"
tqdm = "^4.48"
humanize = "^2.5.0"
dramatiq = {extras = ["redis"], version = "^1.9.0"}
flask-dramatiq = "^0.6.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pytest = "^6.0"
pytest-black = "^0.3.10"
pytest-cov = "^2.10"
pytest-isort = "^1.1"
pytest-flake8 = "^1.0"
pytest-runner = "^5.2"
sphinx = "^3.2"
sphinxcontrib-httpdomain = "^1.7"
sphinx-bootstrap-theme = "^0.7.1"
recommonmark = "^0.6.0"
pyopenssl = "^19.0"
freezegun = "^1.0.0"
pytest-selenium = "^2.0.0"

[tool.poetry.scripts]
fittrackee = 'fittrackee.__main__:main'
fittrackee_init_data = 'fittrackee.__main__:init_data'
fittrackee_upgrade_db = 'fittrackee.__main__:upgrade_db'
fittrackee_worker = 'fittrackee.__main__:dramatiq_worker'

[tool.black]
line-length = 79
skip-string-normalization = true
target-version = ["py37", "py38"]
include = ".py$"
exclude = "migrations"

[tool.isort]
known_third_party = "fittrackee"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
