[tool.poetry]
name = "notify-me-tool"
version = "0.1.0"
description = ""
authors = ["John Hossler <john.m.hossler@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
singleton-decorator = "^1.0.0"
pluggy = "^1.0.0.dev0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-mock = "^3.3.1"

[tool.poetry.scripts]
notify-me = "notify_me_tool.host:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

