
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-24T01:09:49+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f494216a295741d81046228ab064c09223f8b226",
 "version": "0.6.0.post.dev8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
