[tool.poetry]
name = "zql"
version = "0.0.1"
description = "zQL: a SQL builder based on JSON"
authors = ["Anthony Leontiev <ant@devlt.co>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
