
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-09-28T14:07:26+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d2b2dc9cc000f2319a4f4cb39272ede9af1b869c",
 "version": "0.93.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
