# This code-annotations configuration file supports OEP-17, Feature Toggles.

source_path: ./
report_path: reports
safelist_path: .annotation_safe_list.yml
coverage_target: 50.0
annotations:
  documented_elsewhere:
    - ".. documented_elsewhere:":
    - ".. documented_elsewhere_name:":
  feature_toggle:
    - ".. toggle_name:":
    - ".. toggle_implementation:":
        choices: [WaffleFlag, WaffleSwitch, CourseWaffleFlag, ExperimentWaffleFlag, SettingToggle, SettingDictToggle, ConfigurationModel, DjangoSetting]
    - ".. toggle_default:":
    - ".. toggle_description:":
    - ".. toggle_use_cases:":
        choices: [temporary, circuit_breaker, vip, opt_out, opt_in, open_edx]
    - ".. toggle_creation_date:":
    - ".. toggle_target_removal_date:":
    - ".. toggle_warnings:":
    - ".. toggle_tickets:":
extensions:
    python:
        - py
rst_template: doc.rst.j2
