- project:
    templates:
      - openstack-python3-ussuri-jobs
      - openstack-lower-constraints-jobs
      - check-requirements
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - bifrost-integration-tinyipa-ubuntu-bionic
        - bifrost-integration-tinyipa-centos-8
        - bifrost-integration-tinyipa-keystone-ubuntu-bionic
        - bifrost-integration-tinyipa-keystone-centos-8
        # Non-voting jobs
        - bifrost-integration-tinyipa-ubuntu-focal:
            voting: false
        - bifrost-integration-tinyipa-opensuse-15:
            voting: false
        - bifrost-integration-tinyipa-fedora-latest:
            voting: false
        - bifrost-integration-tinyipa-debian-buster:
            voting: false
        - bifrost-integration-dhcp-ubuntu-bionic:
            voting: false
        - bifrost-integration-dibipa-debian-ubuntu-bionic:
            voting: false
        - bifrost-integration-dhcp-centos-8:
            voting: false
        - bifrost-integration-dibipa-debian-centos-8:
            voting: false
        - bifrost-integration-dhcp-opensuse-15:
           voting: false
        - bifrost-integration-dibipa-debian-opensuse-15:
           voting: false
        - bifrost-integration-dhcp-debian-buster:
           voting: false
    gate:
      jobs:
        - bifrost-integration-tinyipa-ubuntu-bionic
        - bifrost-integration-tinyipa-centos-8
        - bifrost-integration-tinyipa-keystone-ubuntu-bionic
        - bifrost-integration-tinyipa-keystone-centos-8
