
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-28T14:10:40-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "9a54bded8a9c500c84369ec74ce3dd36f863fa49",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
