
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-25T04:59:18+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "8e2f52a59f754eb8c16b0996ce0370e026ff055a",
 "version": "1.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
