
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: src/python/arcor2_arserver_data:arcor2_arserver_data_dist

from setuptools import setup

setup(**{
    'author': 'Robo@FIT',
    'author_email': 'imaterna@fit.vut.cz',
    'classifiers': [
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Build Tools',
        'License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)',
        'Programming Language :: Python :: 3.8',
        'Natural Language :: English',
        'Topic :: Scientific/Engineering',
    ],
    'description': 'ARCOR2 - Augmented Reality Collaborative Robot.',
    'license': 'LGPL',
    'long_description': """# arcor2_arserver_data
# Changelog

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),


## [0.8.0] - WIP
### Changed
- The first release of the separated package.""",
    'long_description_content_type': 'text/markdown',
    'name': 'arcor2_arserver_data',
    'version': '0.8.0',
    'package_dir': {
        '': 'src',
    },
    'packages': (
        'arcor2_arserver_data',
        'arcor2_arserver_data.events',
        'arcor2_arserver_data.rpc',
    ),
    'namespace_packages': (
    ),
    'package_data': {
        'arcor2_arserver_data': (
            'VERSION',
            'py.typed',
        ),
    },
    'install_requires': (
        'arcor2==0.8.0',
        'arcor2_calibration_data==0.1.0',
        'dataclasses-jsonschema-rereleased[fast-validation]==2.12.2',
        'dataclasses==0.6',
        'websocket-client==0.57.0',
    ),
})
