#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['django_boilerplate_rest', 'django_boilerplate_rest.migrations']

package_data = \
{'': ['*']}

install_requires = \
['constance',
 'dj_database_url',
 'django_extensions',
 'rest_framework',
 'rest_auth',
 'oauth2_provider',
 'corsheaders',
 'drf_yasg']

setup(name='django_boilerplate_rest',
      version='0.0.6',
      description='Django Boilerplate REST API',
      author='Ravuthz',
      author_email='ravuthz@gmail.com',
      url='https://github.com/ravuthz/django_boilerplate/tree/rest',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.5',
     )
