[tool.poetry]
name = "nb-cli"
version = "0.1.0"
description = "CLI for nonebot2"
authors = ["yanyongyu <yanyongyu_1@126.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.2"
colorama = "^0.4.3"
pyinquirer = "=1.0.3"
pyfiglet = "^0.8.post1"
cookiecutter = "^1.7.2"
docker-compose = "^1.27.2"
nonebot2 = "^2.0.0-alpha.1"

[tool.poetry.dev-dependencies]
yapf = "^0.30.0"

[tool.poetry.scripts]
nb = "nb_cli.__main__:main"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
