stages:
  - dependencies: ['init']
    name: madanalysis5
    scheduler:
      parameters:
        ma5_run_card:
          output: ma5_run_card
          step: init
        ma5_recast_card:
          output: ma5_recast_card
          step: init
        output_folder: '{workdir}/ANALYSIS'
      scheduler_type: singlestep-stage
      step: { $ref: "step.yml" }
