language: python
dist: bionic
sudo: required
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - pip install pip --upgrade
install:
  - pip install -e .[test]
script:
  - pytest --cov
after_success:
  - codecov
