---
init_template: systemd_template.j2
init_dest_dir: /lib/systemd/system/
init_ext: .service
required_packages:
  - mariadb-server
  - python3-dev
  - python3-mysqldb
  - python3-pymysql
  - python3-setuptools
  - libffi-dev
  - libxslt1-dev
  - libssl-dev
  - libxml2-dev
  - nginx
