---
init_template: systemd_template.j2
init_dest_dir: /lib/systemd/system/
init_ext: .service
nginx_user: www-data
mysql_service_name: mysql
required_packages:
  - mariadb-server
  - python-dev
  - python-mysqldb
  - python-configparser
  - libffi-dev
  - libxslt1-dev
  - libssl-dev
  - libxml2-dev
  - nginx
