[tool.poetry]
name = "PyArr"
version = "0.9.3"
description = "A Sonarr and Radarr API Wrapper"
authors = ["Steven Marks <marksie1988@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
keywords = ["sonarr", "radarr", "api", "wrapper"]
homepage = "https://github.com/totaldebug/PyArr"
repository = "https://github.com/totaldebug/PyArr"
documentation = "https://docs.totaldebug.uk/PyArr"

classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Multimedia :: Video",
    "License :: OSI Approved :: MIT License",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.8",
    "Operating System :: OS Independent"
]
packages = [
    {include = "PyArr"}
]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.21.0"

[tool.poetry.dev-dependencies]
black = {version = "^20.8b1", allow-prereleases = true}

[tool.black]
line-length = 88
target_version = ['py38']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
