[tool.poetry]
name = "splunk-otel-python"
version = "0.1.1"
description = "The Splunk distribution of OpenTelemetry Python Instrumentation provides a Python agent that automatically instruments your Python application to capture and report distributed traces to SignalFx APM."
authors = ["Splunk <splunk-oss@splunk.com>"]
license = "Apache-2.0"
packages = [
    { include = "splunk_otel" },
    { include = "splunk_otel/**/*.py" },
]

[tool.poetry.scripts]
splk-py-trace = 'splunk_otel.cmd.trace:run'
splk-py-trace-bootstrap = 'splunk_otel.cmd.bootstrap:run'

[tool.poetry.dependencies]
python = "^3.5"
opentelemetry-api = "^0.13b0"
opentelemetry-sdk = "^0.13b0"
opentelemetry-instrumentation = "^0.13b0"
opentelemetry-exporter-zipkin = "^0.13b0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
