[tool.poetry]
name = "slskit"
version = "2020.9.0"
authors = ["Gediminas Zlatkus <gediminas.zlatkus@gmail.com>"]
description = "Tools for checking Salt state validity"
readme = "README.md"
homepage = "https://github.com/gediminasz/slskit"
repository = "https://github.com/gediminasz/slskit"
keywords = ["salt", "saltstack", "sls"]
classifiers = ["Topic :: Software Development :: Quality Assurance"]

[tool.poetry.dependencies]
python = "3.7.*"
pyyaml = "^5.1"
jsonschema = "^3.2.0"
funcy = "^1.14"
salt = "^3001"
colorlog = "^4.1.0"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.0"
GitPython = "^3.0.5"
mypy = "^0.761"
black = "^19.10b0"
prospector = "^1.2.0"
pytest-snapshot = "^0.4.1"

[tool.poetry.scripts]
slskit = 'slskit:run_module'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
