
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-19T19:02:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "01cfd19b7182a19cfba0f557189316851811453e",
 "version": "0.4.0b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
