[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "hyperglass"
version = "1.0.0-beta.58"
description = "hyperglass is the modern network looking glass that tries to make the internet better."
authors = ["Matt Love <matt@hyperglass.io>"]
readme = "README.md"
homepage = "https://hyperglass.io"
documentation = "https://hyperglass.io"
repository = "https://github.com/checktheroads/hyperglass"
license = "BSD-3-Clause-Clear"
keywords = ["looking glass", "network automation", "isp", "bgp", "routing"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Information Technology",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: JavaScript",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Internet",
    "Topic :: System :: Networking",
]

[tool.poetry.scripts]
hyperglass = "hyperglass.console:CLI"

[tool.poetry.dependencies]
aiofiles = "^0.5.0"
aredis = "^1.1.7"
click = "^7.0"
distro = "^1.5.0"
fastapi = "^0.59"
favicons = "^0.0.8"
gunicorn = "^20.0.4"
httpx = "^0.11"
inquirer = "^2.6.3"
loguru = "^0.4.0"
netmiko = "^2.4.2"
paramiko = "^2.7.1"
Pillow = "^7.0.0"
psutil = "^5.7.2"
py-cpuinfo = "^7.0.0"
pydantic = "^1.4"
PyJWT = "^1.7.1"
python = ">=3.6.1,<4.0"
PyYAML = "^5.3"
redis = "^3.5.3"
rich = "^7.1"
scrapli = {extras = ["asyncssh"], version = "^2020.7.12"}
uvicorn = "^0.11"
uvloop = "^0.14.0"
xmltodict = "^0.12.0"

[tool.poetry.dev-dependencies]
bandit = "^1.6.2"
black = "^19.10b0"
flake8 = "^3.8"
flake8-bandit = "^2.1.2"
flake8-black = "^0.1.1"
flake8-breakpoint = "^1.1.0"
flake8-bugbear = "^20.1.0"
flake8-builtins = "^1.4.2"
flake8-comprehensions = "^3.1.4"
flake8-deprecated = "^1.3"
flake8-docstrings = "^1.5.0"
flake8-eradicate = "^0.2.4"
flake8-if-expr = "^1.0.0"
flake8-isort = "^4.0.0"
flake8-pie = "^0.4.2"
flake8-plugin-utils = "^1.3.1"
flake8-polyfill = "^1.0.2"
flake8-print = "^3.1.4"
isort = "^5.5.3"
mccabe = "^0.6.1"
pep8-naming = "^0.9.1"
pre-commit = "^1.21.0"
stackprinter = "^0.2.3"

[tool.black]
line-length = 88
