doc-warnings: yes
test-warnings: yes
strictness: medium
max-line-length: 79
autodetect: yes
ignore-paths:
    - ci
    - doc
    - examples
    - LICENSES
    - notebooks
pylint:
  disable:
    - dangerous-default-value
