- project:
    name: x/group-based-policy
    templates:
      - openstack-python-jobs
      - publish-to-pypi
    # REVISIT: In the jobs below, the required-projects clause is needed on
    # the master branch to select the correct version of the requirements
    # repository. Otherwise, the master version will be used. It can be
    # eliminated on the stable branches, and on the master branch once this
    # repository's master branch is based on the neutron repository's master
    # branch.
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/stein
        - openstack-tox-py27:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/stein
        - openstack-tox-py35:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/stein
        - openstack-tox-py36:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/stein
        - legacy-group-based-policy-dsvm-functional:
            voting: false
        - legacy-group-based-policy-dsvm-aim:
            voting: true
        - legacy-group-based-policy-dsvm-nfp:
            voting: false
    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/stein
        - openstack-tox-py27:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/stein
        - openstack-tox-py35:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/stein
        - openstack-tox-py36:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/stein
