[tool.poetry]
name = "std-hash"
version = "0.1.1"
description = "Тупое хеширование объектов"
authors = ["Anton Rastyazhenko <rastyazhenko.anton@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
orjson = "^3.3.1"
pydantic = "^1.6.1"
typing = "^3.7.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
