[tool.poetry]
name = "edelweiss-data"
version = "0.2.19"
description = "Python client for EdelweissData"
authors = ["Edelweiss Connect <info@edelweissconnect.com>"]
readme = "README.md"
repository = "https://github.com/DouglasConnect/edelweiss-data-python"
documentation = "https://github.com/DouglasConnect/edelweiss-data-python"

[tool.poetry.dependencies]
python = "^3.6"
pandas = ">=0.23.0"
pyjwt = "^1.5.3"
requests = "^2.18.4"
iso8601 = ">=0.1.11"
docopt = "^0.6.2"

[tool.poetry.dev-dependencies]
pytest = "^5.0"
hypothesis ="^5.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
