language: python

env:
  global:
    - TWINE_USERNAME="anthrotype"
    - secure: RdPIUwIRpUJUOkOZAjHSV+uRzs1OmT+BO+prXSx3A3/HM+dBqIKr3Cya/RR9Jvvg+b9aEm4yw16iTLat+VQtI/vxuxZMKhPiG5Z4hNT8idj7Fg5hOa7+seIHvy5I8EKxaJ8zVYywsIOOVwypKngQTdZhs9IZYtmKXPNzxasH3E6LETj7NcImCtUp8+tfvV6L+yZt2bPi9Oermj5H5G+ato1VmGjSRHqNRUfnEELloU0NGDt/3mENvTsUDr2rf3UMpJGOZ0ky5ScOr1IGnb1M95k+A4DWmExa2g1tLBGD8Gzem8eHVRT6jQiRs8VUdiqBxCa8VVuBi8jC8XVLGmtfC7PPSORGQs8fY+8nazM/T/EqIfHlZAkdYcpgQ7axvQHoltd5ucI+ocCp3MhLSvXxHy3SEQEuRz1U6rGbakBC6qjM+Bzf130gXTzFmzjHdealVB0YWWMmbwn0HqVmQe2r7Paeh3lPwM6d3fSdx96fu8bIuO4QF0C8xaGMltikr4oOOxpWQoGrwmEPjIWt7gAxyxa8SjZPJTeOKlLPQX+0+QH8ZNUgkwBg6dnjWPvLuSShDLD+i/XK8SxUTATieXy/6xjPmLfgRdfYSWGG36OyUnemfiy8VRPNc9YLj5LcQQroorDo9qpDhodgMpyVJVjFyOOYI3I4AyPCH14ENeA18+c=

branches:
  only:
    - master
    - /^v\d+\.\d+.*$/

matrix:
  include:
    - python: 3.6
      env: TOXENV=lint
    - python: 3.6
    - python: 3.7
      dist: xenial
    - python: 3.8
      dist: xenial

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

install: pip install tox-travis

script:
  - tox

after_success:
  - |
    if [[ $TOXENV != lint ]]; then
        if [ -n "$TRAVIS_TAG" ] && [ "$TRAVIS_REPO_SLUG" == "googlefonts/glyphsLib" ] && [ "$TRAVIS_PYTHON_VERSION" == "3.6" ]; then
            pip install --upgrade twine pip setuptools wheel
            python setup.py sdist
            pip wheel --no-deps --wheel-dir dist .
            twine upload dist/*.whl dist/*.zip
        else
            tox -e codecov
        fi
    fi
