[tool.poetry]
name = "volga"
version = "0.1.0"
description = "A python framework for deserialization"
authors = ["Yefri Gaitan <yefrigaitan@gmail.com>", "Ecenaz Jen Ozmen <eo2419@columbia.edu>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
