[tool.poetry]
name = "nbjuniper"
version = "0.1.3"
description = ""
authors = ["Michael Ashton <mashton@ufl.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "^5.3.1"
markdown = "^3.2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
nbjuniper = 'entry:main'
