[tool.poetry]
name = "paraminjector"
version = "0.1.0"
description = ""
authors = ["Joscha Götzer <joscha.goetzer@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
cached-property = "^1.5.1"

[tool.poetry.dev-dependencies]
black = {version = ">=20.8b1", python = "^3.8", markers = "platform_python_implementation == 'CPython'"}
mypy = ">0.770"
pytest = "*"
pytest-asyncio = "*"
pytest-cov = "^2.10.1"
devtools = {extras = ["pygments"], version = "^0.6"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
