[tool.poetry]
name = "imagelab"
version = "0.1.0"
description = "This package is DTU Compute imagelab SDK for research in image analysis, computer vision, and computational imaging."
authors = ["Søren K. S. Gregersen <sorgre@dtu.dk>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
opencv-contrib-python = "^4.4.0"
numpy = "^1.17.2"
scipy = "^1.5.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
